import { Body, Controller, Get, Param, Post, Req } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { Public } from '../../../common/decorators/public.decorator.js';
import { RequireCsrf } from '../../../common/decorators/require-csrf.decorator.js';
import { RequireWorkspace } from '../../../common/decorators/require-workspace.decorator.js';
import { WorkspaceContext } from '../../../common/decorators/workspace-context.decorator.js';
import { ParseMongoIdPipe } from '../../../common/pipes/parse-mongo-id.pipe.js';
import type { WorkspaceRequestContext } from '../../../common/types/workspace-context.js';
import { RequirePermissions } from '../../permissions/decorators/require-permissions.decorator.js';
import { BeginOAuthDto, CreateConnectionDto, CreateMetaConversionDto, OAuthCallbackDto, SelectIntegrationResourcesDto, SyncDto } from '../dto/integration.dto.js';
import { IntegrationService } from '../services/integration.service.js';
import { MetaConversionDeliveryService } from '../services/meta-conversion-delivery.service.js';
import { IntegrationConnectionListResponseDto,IntegrationConnectionResponseDto,IntegrationHealthResponseDto,IntegrationResourceListResponseDto,IntegrationSyncResponseDto,IntegrationValidationResponseDto,MetaConversionQueuedResponseDto,MetaConversionStatusResponseDto,OAuthCallbackResponseDto,OAuthStartResponseDto,OperationAcknowledgementDto,WebhookAcceptedResponseDto } from '../dto/integration-response.dto.js';
import { ApiPublicProviderEndpoint,ApiWorkspaceIntegration } from './integration-openapi.js';
interface IntegrationRawRequest { rawBody?: Buffer; headers: Record<string, string | string[] | undefined> }
@ApiTags('integrations') @Controller('integrations')
export class IntegrationController {
  constructor(private readonly service: IntegrationService,private readonly conversions:MetaConversionDeliveryService) {}
  @Get('connections') @ApiWorkspaceIntegration('List workspace integration connections','integrations.read',IntegrationConnectionListResponseDto) @RequireWorkspace() @RequirePermissions('integrations.read') list(@WorkspaceContext() c:WorkspaceRequestContext){return this.service.list(c);}
  @Post('connections') @ApiWorkspaceIntegration('Create a workspace integration connection','integrations.manage',IntegrationConnectionResponseDto,201) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') create(@WorkspaceContext() c: WorkspaceRequestContext, @Body() d: CreateConnectionDto) { return this.service.create(c, d); }
  @Post('connections/:id/oauth') @ApiWorkspaceIntegration('Begin provider OAuth authorization','integrations.manage',OAuthStartResponseDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') oauth(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string, @Body() d: BeginOAuthDto) { return this.service.beginOAuth(c, id, d.redirectUri); }
  @Public() @Post('oauth/callback') @ApiPublicProviderEndpoint('Complete a provider OAuth callback using single-use state',OAuthCallbackResponseDto) callback(@Body() d: OAuthCallbackDto) { return this.service.callback(d); }
  @Post('connections/:id/disconnect') @ApiWorkspaceIntegration('Disconnect an integration','integrations.manage',OperationAcknowledgementDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') disconnect(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.disconnect(c, id); }
  @Post('connections/:id/refresh') @ApiWorkspaceIntegration('Refresh encrypted provider credentials','integrations.manage',OperationAcknowledgementDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') refresh(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.refresh(c, id); }
  @Get('connections/:id/resources') @ApiWorkspaceIntegration('Discover selectable provider resources','integrations.read',IntegrationResourceListResponseDto) @RequireWorkspace() @RequirePermissions('integrations.read') resources(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.discoverResources(c, id); }
  @Post('connections/:id/resources') @ApiWorkspaceIntegration('Persist selected provider resources','integrations.manage',OperationAcknowledgementDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') selectResources(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string, @Body() d: SelectIntegrationResourcesDto) { return this.service.selectResources(c, id, d); }
  @Post('connections/:id/webhooks/subscribe') @ApiWorkspaceIntegration('Subscribe selected provider resources to webhooks','integrations.manage',OperationAcknowledgementDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') subscribe(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.subscribeWebhooks(c, id); }
  @Post('connections/:id/conversions') @ApiWorkspaceIntegration('Queue a Meta Conversions API event','integrations.manage',MetaConversionQueuedResponseDto,201) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') conversion(@WorkspaceContext()c:WorkspaceRequestContext,@Param('id',ParseMongoIdPipe)id:string,@Body()d:CreateMetaConversionDto){return this.conversions.enqueue(c,id,d);}
  @Get('connections/:id/conversions/:deliveryId') @ApiWorkspaceIntegration('Get a Meta conversion delivery status','integrations.read',MetaConversionStatusResponseDto) @RequireWorkspace() @RequirePermissions('integrations.read') conversionStatus(@WorkspaceContext()c:WorkspaceRequestContext,@Param('id',ParseMongoIdPipe)id:string,@Param('deliveryId',ParseMongoIdPipe)deliveryId:string){return this.conversions.status(c,id,deliveryId);}
  @Post('connections/:id/validate') @ApiWorkspaceIntegration('Validate provider credentials','integrations.manage',IntegrationValidationResponseDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') validate(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.validate(c, id); }
  @Post('connections/:id/sync') @ApiWorkspaceIntegration('Queue an idempotent provider synchronization','integrations.manage',IntegrationSyncResponseDto,202) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.manage') sync(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string, @Body() d: SyncDto) { return this.service.sync(c, id, d); }
  @Post('connections/:id/health') @ApiWorkspaceIntegration('Check provider connection health','integrations.read',IntegrationHealthResponseDto) @RequireCsrf() @RequireWorkspace() @RequirePermissions('integrations.read') health(@WorkspaceContext() c: WorkspaceRequestContext, @Param('id', ParseMongoIdPipe) id: string) { return this.service.health(c, id); }
  @Public() @Post('webhooks/:workspaceId/:connectionId') @ApiPublicProviderEndpoint('Receive a verified provider webhook',WebhookAcceptedResponseDto) webhook(@Param('workspaceId', ParseMongoIdPipe) workspaceId: string, @Param('connectionId', ParseMongoIdPipe) connectionId: string, @Req() request: IntegrationRawRequest) { if (!request.rawBody) throw new Error('Raw body is unavailable'); const headers = Object.fromEntries(Object.entries(request.headers).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value])); return this.service.webhook(workspaceId, connectionId, request.rawBody, headers); }
}
