import { FileText, Globe2, HelpCircle, Layers3, Plus, Search, Upload } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useToast } from '@/app/providers';
import { Badge, Button, EmptyState, Input, Modal, Tabs } from '@/shared/ui';
import { useAgentData } from '../hooks/use-agent-data';
import type { KnowledgeKind, KnowledgeSource } from '../types/agent.types';

const tabKinds: Array<{ kind: KnowledgeKind; label: string }> = [{ kind: 'document', label: 'Documents' }, { kind: 'website', label: 'Websites' }, { kind: 'faq', label: 'FAQs' }, { kind: 'collection', label: 'Collections' }];
const icons = { document: FileText, website: Globe2, faq: HelpCircle, collection: Layers3 };

export function KnowledgeBasePage() {
  const data = useAgentData(); const { notify } = useToast(); const [search, setSearch] = useState(''); const [uploadOpen, setUploadOpen] = useState(false); const [crawlOpen, setCrawlOpen] = useState(false); const [websiteUrl, setWebsiteUrl] = useState(''); const [urlError, setUrlError] = useState<string>();
  const filtered = useMemo(() => data.sources.filter((source) => `${source.name} ${source.description}`.toLowerCase().includes(search.toLowerCase())), [data.sources, search]);
  const addProcessing = (source: KnowledgeSource) => { data.addSource(source); window.setTimeout(() => data.updateSource(source.id, { status: 'ready' }), 1_500); };
  const sourceGrid = (kind: KnowledgeKind) => {
    const sources = filtered.filter((source) => source.kind === kind); const Icon = icons[kind];
    return sources.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sources.map((source) => { const assigned = data.agents.filter((agent) => agent.knowledgeSourceIds.includes(source.id)); return <article className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" key={source.id}><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300"><Icon size={17} /></span><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{source.name}</h2><Badge className="mt-1" tone={source.status === 'ready' ? 'success' : source.status === 'processing' ? 'warning' : 'danger'}>{source.status}</Badge></div></div><p className="mt-3 min-h-10 text-sm text-slate-500">{source.description}</p><div className="mt-3 flex flex-wrap gap-1">{assigned.length ? assigned.map((agent) => <Badge key={agent.id} tone="neutral">{agent.name}</Badge>) : <span className="text-xs text-slate-500">Not assigned to an agent</span>}</div><p className="mt-3 border-t border-slate-200 pt-3 text-xs text-slate-500 dark:border-slate-700">{source.size ?? source.url ?? `${source.items ?? 0} items`} · Updated {new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(source.updatedAt))}</p></article>; })}</div> : <EmptyState description={`No ${kind} sources match your search.`} icon={<Icon size={26} />} title={`No ${kind}s found`} />;
  };
  return <div className="grid gap-6"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-medium text-indigo-600 dark:text-indigo-400">Agent knowledge</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Knowledge base</h1><p className="mt-1 text-sm text-slate-500">Manage mock sources and assign them from individual agent settings.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setCrawlOpen(true)} variant="outline"><Globe2 size={16} />Crawl website</Button><Button onClick={() => setUploadOpen(true)}><Upload size={16} />Upload document</Button></div></header><Input leading={<Search size={16} />} onChange={(event) => setSearch(event.target.value)} placeholder="Search documents, websites, FAQs, and collections…" value={search} /><Tabs defaultValue="document" items={tabKinds.map(({ kind, label }) => ({ label: `${label} (${filtered.filter((source) => source.kind === kind).length})`, value: kind, content: sourceGrid(kind) }))} />
    <Modal onClose={() => setUploadOpen(false)} open={uploadOpen} title="Upload document" description="Simulate document processing without uploading to a server."><label className="grid cursor-pointer place-items-center rounded-xl border-2 border-dashed border-slate-300 p-8 text-center dark:border-slate-700"><Upload className="mb-2 text-indigo-500" /><strong>Select a PDF, DOCX, or TXT file</strong><span className="mt-1 text-sm text-slate-500">The mock status changes from processing to ready.</span><input accept=".pdf,.doc,.docx,.txt" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; addProcessing({ id: crypto.randomUUID(), kind: 'document', name: file.name, description: 'Newly uploaded mock knowledge document.', status: 'processing', updatedAt: new Date().toISOString(), size: `${Math.max(1, Math.round(file.size / 1024))} KB` }); setUploadOpen(false); notify({ title: 'Document processing started', tone: 'success' }); }} type="file" /></label></Modal>
    <Modal onClose={() => { setCrawlOpen(false); setUrlError(undefined); }} open={crawlOpen} title="Crawl website" description="Create a simulated website source. No network request is made."><div className="grid gap-4"><Input error={urlError} label="Website URL" onChange={(event) => { setWebsiteUrl(event.target.value); setUrlError(undefined); }} placeholder="https://example.com/help" type="url" value={websiteUrl} /><Button disabled={!websiteUrl.trim()} onClick={() => { let parsed: URL; try { parsed = new URL(websiteUrl); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Unsupported protocol'); } catch { setUrlError('Enter a valid HTTP or HTTPS website URL.'); return; } addProcessing({ id: crypto.randomUUID(), kind: 'website', name: parsed.hostname, description: 'Mock crawled website content.', status: 'processing', updatedAt: new Date().toISOString(), url: websiteUrl }); setWebsiteUrl(''); setCrawlOpen(false); notify({ title: 'Mock crawl started', tone: 'success' }); }}><Plus size={16} />Start crawl</Button></div></Modal>
  </div>;
}

export default KnowledgeBasePage;
