import { CalendarDays, KeyRound, Link2, Mail, MessageCircle, RefreshCw, Search, ShoppingBag, Unplug, Webhook, Zap } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Input, Modal, Tabs } from '@/shared/ui';

interface Integration { id: string; name: string; category: string; description: string; connected: boolean; icon: typeof Mail }
const seed: Integration[] = [
  { id: 'facebook', name: 'Facebook', category: 'Social', description: 'Sync lead ads and Messenger conversations.', connected: true, icon: MessageCircle },
  { id: 'instagram', name: 'Instagram', category: 'Social', description: 'Manage direct messages and audience activity.', connected: false, icon: MessageCircle },
  { id: 'whatsapp', name: 'WhatsApp', category: 'Messaging', description: 'Connect a WhatsApp Business number.', connected: true, icon: MessageCircle },
  { id: 'gmail', name: 'Gmail', category: 'Email', description: 'Send and receive workspace email.', connected: true, icon: Mail },
  { id: 'outlook', name: 'Outlook', category: 'Email', description: 'Connect Microsoft email and contacts.', connected: false, icon: Mail },
  { id: 'google-calendar', name: 'Google Calendar', category: 'Calendar', description: 'Synchronize appointments and availability.', connected: true, icon: CalendarDays },
  { id: 'stripe', name: 'Stripe', category: 'Commerce', description: 'Sync customers, payments, and subscriptions.', connected: false, icon: Zap },
  { id: 'shopify', name: 'Shopify', category: 'Commerce', description: 'Import customers and order activity.', connected: false, icon: ShoppingBag },
  { id: 'highlevel', name: 'HighLevel', category: 'CRM', description: 'Migrate contacts and opportunities.', connected: false, icon: RefreshCw },
  { id: 'webhooks', name: 'Webhooks', category: 'Developer', description: 'Send event payloads to external endpoints.', connected: true, icon: Webhook },
];

export function IntegrationsPage() {
  const [items, setItems] = useState(seed); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Integration | null>(null); const [keys, setKeys] = useState(['amp_live_••••••••c82f']);
  const cards = <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())).map((item) => { const Icon = item.icon; return <article className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900" key={item.id}><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-lg bg-slate-100 dark:bg-slate-800"><Icon size={20} /></span><div><h2 className="font-semibold">{item.name}</h2><Badge tone={item.connected ? 'success' : 'neutral'}>{item.connected ? 'Connected' : item.category}</Badge></div></div><p className="mt-4 min-h-10 text-sm text-slate-500">{item.description}</p><Button className="mt-4 w-full" onClick={() => item.connected ? setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, connected: false } : entry)) : setSelected(item)} variant={item.connected ? 'ghost' : 'outline'}>{item.connected ? <><Unplug size={15} />Disconnect</> : <><Link2 size={15} />Connect</>}</Button></article>; })}</div>;
  const developer = <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 font-semibold"><Webhook size={17} />Webhooks</h2><p className="mt-2 text-sm text-slate-500">Mock endpoint: https://hooks.example.com/crm-events</p><Button className="mt-4" variant="outline">Add endpoint</Button></section><section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 font-semibold"><KeyRound size={17} />API keys</h2>{keys.map((key) => <div className="mt-3 rounded-lg bg-slate-100 p-3 font-mono text-sm dark:bg-slate-800" key={key}>{key}</div>)}<Button className="mt-4" onClick={() => setKeys((current) => [...current, `amp_test_••••${current.length + 1}`])} variant="outline">Generate mock key</Button></section></div>;
  return <div className="grid gap-6"><header><p className="text-sm font-medium text-indigo-600">Connected apps</p><h1 className="text-3xl font-bold">Integrations</h1><p className="text-sm text-slate-500">Connect communication, commerce, calendar, and developer tools.</p></header><Input leading={<Search size={16} />} onChange={(event) => setSearch(event.target.value)} placeholder="Search integrations…" value={search} /><Tabs defaultValue="apps" items={[{ label: 'App marketplace', value: 'apps', content: cards }, { label: 'Webhooks & API keys', value: 'developer', content: developer }]} /><Modal onClose={() => setSelected(null)} open={Boolean(selected)} title={`Connect ${selected?.name ?? 'integration'}`} description="This is a frontend-only connection simulation."><div className="grid gap-4"><Input label="Account identifier" placeholder="account@example.com" /><Input label="Access token" placeholder="Mock token" type="password" /><Button onClick={() => { if (selected) setItems((current) => current.map((item) => item.id === selected.id ? { ...item, connected: true } : item)); setSelected(null); }}>Connect mock account</Button></div></Modal></div>;
}

export default IntegrationsPage;
