import { Bell, Building2, Database, Globe2, Lock, Palette, Plus, Save, Shield, SlidersHorizontal, UserRound } from 'lucide-react';
import { useToast } from '@/app/providers';
import { Badge, Button, Checkbox, Input, Select, Switch, Table, Tabs, Textarea } from '@/shared/ui';

const panel = (title: string, description: string, children: React.ReactNode) => <section className="max-w-3xl rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p><div className="mt-5 grid gap-4">{children}</div></section>;

export function SettingsPage() {
  const { notify } = useToast(); const save = () => notify({ title: 'Settings saved locally', tone: 'success' });
  const workspace = panel('Workspace settings', 'Update organization defaults and locale.', <><Input label="Workspace name" defaultValue="Acme Studio" /><div className="grid gap-4 sm:grid-cols-2"><Select label="Timezone" options={[{ label: 'Asia/Karachi', value: 'pk' }, { label: 'America/New York', value: 'ny' }]} /><Select label="Currency" options={[{ label: 'USD', value: 'usd' }, { label: 'EUR', value: 'eur' }]} /></div><Button className="justify-self-start" onClick={save}><Save size={15} />Save workspace</Button></>);
  const profile = panel('Profile', 'Manage your personal account details.', <><Input label="Full name" defaultValue="Alex Morgan" /><Input label="Email" defaultValue="alex@acme.io" type="email" /><Textarea label="Bio" defaultValue="Revenue operations lead at Acme Studio." /><Button className="justify-self-start" onClick={save}>Update profile</Button></>);
  const branding = panel('Branding', 'Customize the visual identity used across customer experiences.', <><Input label="Brand name" defaultValue="Acme" /><div className="grid gap-4 sm:grid-cols-2"><Input label="Primary color" defaultValue="#4f46e5" type="color" /><Input label="Logo" type="file" /></div><Button className="justify-self-start" onClick={save}>Save branding</Button></>);
  const domains = panel('Domains', 'Configure hosted pages and sending domains.', <><div className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 dark:border-slate-700"><Globe2 size={17} /><div><strong className="text-sm">pages.acme.example</strong><p className="text-xs text-slate-500">SSL active</p></div><Badge className="ml-auto" tone="success">Verified</Badge></div><Button className="justify-self-start" variant="outline"><Plus size={15} />Add domain</Button></>);
  const notifications = panel('Notifications', 'Choose when the workspace should notify you.', <><Switch checked label="New lead alerts" /><Switch checked label="Assignment notifications" /><Switch checked={false} label="Weekly performance summary" /><Switch checked label="Billing notifications" /></>);
  const security = panel('Security', 'Protect accounts and review session policies.', <><Switch checked label="Require two-factor authentication" /><Select label="Session timeout" options={[{ label: '8 hours', value: '8' }, { label: '24 hours', value: '24' }]} /><Button className="justify-self-start" variant="danger">Sign out all sessions</Button></>);
  const customFields = panel('Custom fields', 'Define reusable data fields for CRM records.', <><Table columns={[{ key: 'name', header: 'Field', render: (row: { name: string; type: string }) => row.name }, { key: 'type', header: 'Type', render: (row) => <Badge>{row.type}</Badge> }]} getRowKey={(row) => row.name} rows={[{ name: 'Customer tier', type: 'Select' }, { name: 'Annual value', type: 'Currency' }, { name: 'Renewal date', type: 'Date' }]} /><Button className="justify-self-start" variant="outline"><Plus size={15} />Add field</Button></>);
  const pipelines = panel('Pipeline settings', 'Manage stages and default deal behavior.', <>{['New lead', 'Qualified', 'Proposal sent', 'Negotiation', 'Won', 'Lost'].map((stage, index) => <div className="flex items-center gap-3 rounded-lg border border-slate-200 p-3 dark:border-slate-700" key={stage}><span className="grid size-7 place-items-center rounded bg-slate-100 text-xs dark:bg-slate-800">{index + 1}</span><strong className="text-sm">{stage}</strong><Input aria-label={`${stage} probability`} className="ml-auto w-24" defaultValue={index < 4 ? `${index * 20 + 10}` : index === 4 ? '100' : '0'} type="number" /></div>)}</>);
  const audit = panel('Audit logs', 'Review important workspace changes.', <Table columns={[{ key: 'event', header: 'Event', render: (row: { event: string; actor: string; time: string }) => <strong>{row.event}</strong> }, { key: 'actor', header: 'Actor', render: (row) => row.actor }, { key: 'time', header: 'Time', render: (row) => row.time }]} getRowKey={(row) => `${row.event}-${row.time}`} rows={[{ event: 'Agent published', actor: 'Alex Morgan', time: '10:42' }, { event: 'Member invited', actor: 'Jordan Lee', time: 'Yesterday' }, { event: 'Domain verified', actor: 'System', time: 'Jul 21' }]} />);
  return <div className="grid gap-6"><header><p className="text-sm font-medium text-indigo-600">Workspace configuration</p><h1 className="text-3xl font-bold">Settings</h1><p className="text-sm text-slate-500">Manage workspace identity, security, data, and preferences.</p></header><Tabs defaultValue="workspace" items={[{ label: 'Workspace', value: 'workspace', content: workspace }, { label: 'Profile', value: 'profile', content: profile }, { label: 'Branding', value: 'branding', content: branding }, { label: 'Domains', value: 'domains', content: domains }, { label: 'Notifications', value: 'notifications', content: notifications }, { label: 'Security', value: 'security', content: security }, { label: 'Custom fields', value: 'fields', content: customFields }, { label: 'Pipelines', value: 'pipelines', content: pipelines }, { label: 'Audit logs', value: 'audit', content: audit }]} /><div className="sr-only"><Building2 /><UserRound /><Palette /><Bell /><Lock /><Shield /><Database /><SlidersHorizontal /><Checkbox label="placeholder" /></div></div>;
}

export default SettingsPage;
