import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { WorkspaceRequestContext } from '../../../common/types/workspace-context.js';
import { FilesRepository } from '../../files/repositories/files.repository.js';
import { FilesService } from '../../files/services/files.service.js';
import { IntegrationService } from '../../integrations/services/integration.service.js';
import { MetaAdsService } from '../../integrations/providers/meta/meta-ads.service.js';
import { MetaInsightsService } from '../../integrations/providers/meta/meta-insights.service.js';
import type { CreateMetaAdDto, CreateMetaAdSetDto, CreateMetaCampaignDto, CreateMetaCreativeDto, CreateMetaCustomAudienceDto, CreateMetaLookalikeDto, MetaInsightsQueryDto, UpdateMetaAdDto, UpdateMetaAdSetDto, UpdateMetaCampaignDto } from '../dto/meta-campaign.dto.js';
import { CampaignRepository } from '../repositories/campaign.repository.js';
import { internalStatusFromMeta,mapMetaCampaign } from '../providers/meta-campaign.mapper.js';
import { CampaignService } from './campaign.service.js';
import { WorkflowService } from '../../workflows/services/workflow.service.js';

@Injectable()
export class MetaCampaignManagementService {
  constructor(private readonly campaigns:CampaignRepository,private readonly campaignService:CampaignService,private readonly integrations:IntegrationService,private readonly meta:MetaAdsService,private readonly insights:MetaInsightsService,private readonly files:FilesService,private readonly fileRepository:FilesRepository,private readonly workflows:WorkflowService){}
  async list(c:WorkspaceRequestContext,connectionId:string){const context=await this.integrations.context(c.workspaceId,connectionId),[internal,provider]=await Promise.all([this.campaigns.listCampaigns(c.workspaceId,'meta'),this.meta.listCampaigns(context)]),byId=new Map(provider.map((value)=>[String(value.id),value]));return internal.filter((campaign)=>String(campaign.integrationConnectionId)===connectionId).map((campaign)=>mapMetaCampaign(campaign,byId.get(campaign.externalCampaignId??'')));}
  async get(c:WorkspaceRequestContext,id:string){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign);return{campaign,provider:await this.meta.getCampaign(context,campaign.externalCampaignId!)};}
  async create(c:WorkspaceRequestContext,d:CreateMetaCampaignDto){const internal=await this.campaignService.create(c,{name:d.name,channel:'social',communicationType:'marketing',timezone:d.timezone,variants:[{id:'meta-default',weight:100,content:d.name}],personalizationDefaults:{},quietHours:{startMinutes:1320,endMinutes:480}}),context=await this.integrations.context(c.workspaceId,d.connectionId);try{const provider=await this.meta.createCampaign(context,{name:d.name,objective:d.objective,status:d.status,specialAdCategories:d.specialAdCategories}),externalCampaignId=String(provider.id??'');if(!externalCampaignId)throw new BadRequestException('Meta did not return a campaign ID');const campaign=await this.campaigns.updateCampaign(c.workspaceId,String(internal._id),{$set:{externalProvider:'meta',externalCampaignId,integrationConnectionId:d.connectionId,status:internalStatusFromMeta(d.status),providerMetadata:{objective:d.objective,specialAdCategories:d.specialAdCategories,effectiveStatus:d.status}}});return{campaign,provider};}catch(error){await this.campaigns.updateCampaign(c.workspaceId,String(internal._id),{$set:{status:'failed',providerMetadata:{syncError:error instanceof Error?error.message:'Meta campaign creation failed'}}});throw error;}}
  async update(c:WorkspaceRequestContext,id:string,d:UpdateMetaCampaignDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId),input={...(d.name?{name:d.name}:{}),...(d.objective?{objective:d.objective}:{})},provider=await this.meta.updateCampaign(context,campaign.externalCampaignId!,input);await this.campaigns.updateCampaign(c.workspaceId,id,{$set:{...(d.name?{name:d.name}:{}),...(d.objective?{'providerMetadata.objective':d.objective}:{})}});return provider;}
  async status(c:WorkspaceRequestContext,id:string,connectionId:string,status:'ACTIVE'|'PAUSED'|'ARCHIVED'){const campaign=await this.metaCampaign(c.workspaceId,id),previousStatus=campaign.status,context=await this.contextFor(c.workspaceId,campaign,connectionId),provider=await this.meta.setStatus(context,campaign.externalCampaignId!,status),internalStatus=status==='ACTIVE'?'running':status==='PAUSED'?'paused':'archived';await this.campaigns.updateCampaign(c.workspaceId,id,{$set:{status:internalStatus,'providerMetadata.effectiveStatus':status}});await this.workflows.triggerEvent(c.workspaceId,'campaign.status_changed',`campaign:${id}:status:${status}`,{campaignId:id,provider:'meta',externalCampaignId:campaign.externalCampaignId,connectionId,previousStatus,status:internalStatus,providerStatus:status});return provider;}
  async listAdSets(c:WorkspaceRequestContext,id:string,connectionId:string){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,connectionId);return this.meta.listAdSets(context,campaign.externalCampaignId!);}
  async createAdSet(c:WorkspaceRequestContext,id:string,d:CreateMetaAdSetDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId),targeting={...d.targeting,...(d.publisherPlatforms?{publisher_platforms:d.publisherPlatforms}:{}),...(d.facebookPositions?{facebook_positions:d.facebookPositions}:{}),...(d.instagramPositions?{instagram_positions:d.instagramPositions}:{})},provider=await this.meta.createAdSet(context,{name:d.name,campaign_id:campaign.externalCampaignId,billing_event:d.billingEvent,optimization_goal:d.optimizationGoal,targeting,daily_budget:d.dailyBudget,...(d.lifetimeBudget?{lifetime_budget:d.lifetimeBudget}:{}),...(d.startTime?{start_time:d.startTime}:{}),...(d.endTime?{end_time:d.endTime}:{}),status:d.status});await this.appendConfiguration(c.workspaceId,id,'adSets',provider);return provider;}
  async updateAdSet(c:WorkspaceRequestContext,id:string,adSetId:string,d:UpdateMetaAdSetDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId);return this.meta.updateAdSet(context,adSetId,{...(d.name?{name:d.name}:{}),...(d.dailyBudget?{daily_budget:d.dailyBudget}:{}),...(d.lifetimeBudget?{lifetime_budget:d.lifetimeBudget}:{}),...(d.optimizationGoal?{optimization_goal:d.optimizationGoal}:{}),...(d.billingEvent?{billing_event:d.billingEvent}:{}),...(d.targeting?{targeting:d.targeting}:{}),...(d.startTime?{start_time:d.startTime}:{}),...(d.endTime?{end_time:d.endTime}:{})});}
  async adSetStatus(c:WorkspaceRequestContext,id:string,adSetId:string,connectionId:string,status:'ACTIVE'|'PAUSED'|'ARCHIVED'){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,connectionId);return this.meta.setStatus(context,adSetId,status);}
  async listAds(c:WorkspaceRequestContext,id:string,connectionId:string,adSetId?:string){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,connectionId);return this.meta.listAds(context,adSetId);}
  async getAd(c:WorkspaceRequestContext,id:string,adId:string,connectionId:string){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,connectionId);return this.meta.getAd(context,adId);}
  async createAd(c:WorkspaceRequestContext,id:string,d:CreateMetaAdDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId),provider=await this.meta.createAd(context,{name:d.name,adset_id:d.adSetId,creative:{creative_id:d.creativeId},status:d.status});await this.appendConfiguration(c.workspaceId,id,'ads',provider);return provider;}
  async updateAd(c:WorkspaceRequestContext,id:string,adId:string,d:UpdateMetaAdDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId);return this.meta.updateAd(context,adId,{...(d.name?{name:d.name}:{}),...(d.creativeId?{creative:{creative_id:d.creativeId}}:{})});}
  async adStatus(c:WorkspaceRequestContext,id:string,adId:string,connectionId:string,status:'ACTIVE'|'PAUSED'|'ARCHIVED'){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,connectionId);return this.meta.setStatus(context,adId,status);}
  async createCreative(c:WorkspaceRequestContext,id:string,d:CreateMetaCreativeDto){const campaign=await this.metaCampaign(c.workspaceId,id),context=await this.contextFor(c.workspaceId,campaign,d.connectionId),file=await this.fileRepository.get(c.workspaceId,d.mediaFileId);if(file.status!=='active'||file.scanStatus!=='clean')throw new BadRequestException('Media asset is not active and malware-scanned');if(!file.mimeType.startsWith('image/')&&!file.mimeType.startsWith('video/'))throw new BadRequestException('Meta creatives require an image or video asset');const{url}=await this.files.download(c,d.mediaFileId);let creativeData:Record<string,unknown>;if(file.mimeType.startsWith('video/')){const uploaded=await this.meta.createVideo(context,url,file.originalName),videoId=String(uploaded.id??'');creativeData={video_data:{video_id:videoId,message:d.primaryText,title:d.headline,link_description:d.description,call_to_action:{type:d.callToAction,value:{link:d.destinationUrl}}}};}else{const uploaded=await this.meta.createImage(context,url),images=uploaded.images as Record<string,{hash?:string}>|undefined,imageHash=images?Object.values(images)[0]?.hash:undefined;if(!imageHash)throw new BadRequestException('Meta image upload did not return an image hash');creativeData={link_data:{image_hash:imageHash,link:d.destinationUrl,message:d.primaryText,name:d.headline,description:d.description,call_to_action:{type:d.callToAction,value:{link:d.destinationUrl}}}};}const provider=await this.meta.createCreative(context,{name:d.name,object_story_spec:{page_id:d.pageId,...(d.instagramActorId?{instagram_actor_id:d.instagramActorId}:{}),...creativeData}});await this.files.reference(c,d.mediaFileId,{type:'meta_campaign',id});await this.appendConfiguration(c.workspaceId,id,'creatives',{...provider,mediaFileId:d.mediaFileId});return provider;}
  async audiences(c:WorkspaceRequestContext,connectionId:string){const context=await this.integrations.context(c.workspaceId,connectionId);const[custom,saved]=await Promise.all([this.meta.listCustomAudiences(context),this.meta.listSavedAudiences(context)]);return{custom,saved};}
  async customAudience(c:WorkspaceRequestContext,d:CreateMetaCustomAudienceDto){return this.meta.createCustomAudience(await this.integrations.context(c.workspaceId,d.connectionId),d);}
  async report(c:WorkspaceRequestContext,d:MetaInsightsQueryDto){const since=new Date(d.since),until=new Date(d.until),days=(until.getTime()-since.getTime())/86_400_000;if(!Number.isFinite(days)||days<0||days>93)throw new BadRequestException('Meta Insights date range must be between 1 and 93 days');return this.insights.report(await this.integrations.context(c.workspaceId,d.connectionId),{since:d.since.slice(0,10),until:d.until.slice(0,10),level:d.level,daily:d.daily,limit:d.limit,...(d.cursor?{cursor:d.cursor}:{})});}
  async targeting(c:WorkspaceRequestContext,connectionId:string,query:string,type?:string){return this.meta.searchTargeting(await this.integrations.context(c.workspaceId,connectionId),query,type);}
  async lookalike(c:WorkspaceRequestContext,d:CreateMetaLookalikeDto){return this.meta.createLookalike(await this.integrations.context(c.workspaceId,d.connectionId),d);}
  private async metaCampaign(workspaceId:string,id:string){const campaign=await this.campaigns.campaign(workspaceId,id);if(campaign.externalProvider!=='meta'||!campaign.externalCampaignId)throw new NotFoundException('Meta campaign not found');return campaign;}
  private async contextFor(workspaceId:string,campaign:{integrationConnectionId:unknown},requested?:string){const connectionId=requested??String(campaign.integrationConnectionId??'');if(!connectionId||String(campaign.integrationConnectionId)!==connectionId)throw new BadRequestException('Campaign is not associated with this Meta connection');return this.integrations.context(workspaceId,connectionId);}
  private async appendConfiguration(workspaceId:string,id:string,key:string,value:Record<string,unknown>){const version=await this.campaigns.draft(workspaceId,id),configuration={...(version?.providerConfiguration??{})},items=Array.isArray(configuration[key])?configuration[key] as Record<string,unknown>[]:[];configuration[key]=[...items,value];await this.campaigns.updateProviderConfiguration(workspaceId,id,configuration);}
}
