export const PERMISSIONS = [
  'contacts.read',
  'contacts.create',
  'contacts.update',
  'contacts.delete',
  'companies.read',
  'companies.create',
  'companies.update',
  'companies.delete',
  'leads.read',
  'leads.create',
  'leads.update',
  'leads.delete',
  'leads.convert',
  'deals.read',
  'deals.manage',
  'pipelines.read',
  'pipelines.manage',
  'tasks.read',
  'tasks.manage',
  'calendar.read',
  'appointments.read',
  'appointments.manage',
  'services.read',
  'services.manage',
  'availability.read',
  'availability.manage',
  'booking-links.read',
  'booking-links.manage',
  'inbox.reply',
  'inbox.read',
  'inbox.manage',
  'workflows.publish',
  'workflows.read',
  'workflows.run',
  'workflows.manage',
  'agents.manage',
  'billing.manage',
  'campaigns.read',
  'campaigns.manage',
  'campaigns.approve',
  'team.manage',
  'admin.access',
  'integrations.read',
  'integrations.manage',
  'files.read',
  'files.manage',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const PERMISSION_GROUPS = {
  contactsViewer: ['contacts.read'],
  contactsEditor: ['contacts.read', 'contacts.create', 'contacts.update'],
  contactsManager: ['contacts.read', 'contacts.create', 'contacts.update', 'contacts.delete'],
  dealsManager: ['deals.read', 'deals.manage'],
  crmManager: [
    'contacts.read', 'contacts.create', 'contacts.update', 'contacts.delete',
    'companies.read', 'companies.create', 'companies.update', 'companies.delete',
    'leads.read', 'leads.create', 'leads.update', 'leads.delete', 'leads.convert',
    'deals.read', 'deals.manage', 'pipelines.read', 'pipelines.manage',
  ],
  workspaceManager: ['team.manage', 'workflows.read', 'workflows.run', 'workflows.manage', 'workflows.publish', 'agents.manage'],
  schedulingManager: [
    'tasks.read', 'tasks.manage', 'calendar.read', 'appointments.read', 'appointments.manage',
    'services.read', 'services.manage', 'availability.read', 'availability.manage',
    'booking-links.read', 'booking-links.manage',
  ],
  inboxAgent: ['inbox.read', 'inbox.reply'],
  inboxManager: ['inbox.read', 'inbox.reply', 'inbox.manage'],
  campaignManager: ['campaigns.read', 'campaigns.manage', 'campaigns.approve'],
  integrationManager: ['integrations.read', 'integrations.manage'],
  fileManager: ['files.read', 'files.manage'],
} as const satisfies Record<string, readonly Permission[]>;

export type PermissionGroup = keyof typeof PERMISSION_GROUPS;

export const ALLOWED_ADMIN_WILDCARDS = ['admin.*'] as const;
