import { ArrowRight, Filter, Plus, TrendingUp } from 'lucide-react';
import { Badge, Button, MetricCard } from '@/shared/ui';

const funnels = [{ name: 'Product-led demo', status: 'active', visitors: 18420, conversion: 12.8, revenue: 184200, steps: ['Landing page', 'Lead form', 'Demo booked', 'Opportunity'] }, { name: 'Webinar acquisition', status: 'active', visitors: 9820, conversion: 18.4, revenue: 96200, steps: ['Registration', 'Attended', 'Follow-up', 'Qualified'] }, { name: 'Partner referral', status: 'draft', visitors: 0, conversion: 0, revenue: 0, steps: ['Partner page', 'Referral form', 'Sales review'] }];

export function FunnelsPage() {
  return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-indigo-600">Conversion journeys</p><h1 className="text-3xl font-bold">Funnels</h1><p className="text-sm text-slate-500">Track multi-step acquisition and revenue paths.</p></div><Button><Plus size={16} />Create funnel</Button></header><div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={<Filter />} label="Active funnels" value="2" /><MetricCard icon={<TrendingUp />} label="Blended conversion" value="15.6%" /><MetricCard label="Attributed revenue" value="$280,400" /></div><div className="grid gap-5">{funnels.map((funnel) => <article className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900" key={funnel.name}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{funnel.name}</h2><Badge className="mt-1" tone={funnel.status === 'active' ? 'success' : 'warning'}>{funnel.status}</Badge></div><div className="flex gap-6 text-sm"><span><strong className="block">{funnel.visitors.toLocaleString()}</strong><span className="text-xs text-slate-500">Visitors</span></span><span><strong className="block">{funnel.conversion}%</strong><span className="text-xs text-slate-500">Conversion</span></span><span><strong className="block">${funnel.revenue.toLocaleString()}</strong><span className="text-xs text-slate-500">Revenue</span></span></div></div><div className="mt-5 flex min-w-0 items-center gap-2 overflow-x-auto pb-2">{funnel.steps.map((step, index) => <div className="contents" key={step}><div className="min-w-40 rounded-lg border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-800"><span className="text-xs text-slate-500">Step {index + 1}</span><strong className="block text-sm">{step}</strong><div className="mt-2 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${Math.max(20, 100 - index * 22)}%` }} /></div></div>{index < funnel.steps.length - 1 ? <ArrowRight className="shrink-0 text-slate-400" size={18} /> : null}</div>)}</div></article>)}</div></div>;
}

export default FunnelsPage;
