import { CalendarDays, Clock, Link2, Plus, Users } from 'lucide-react';
import { useState } from 'react';
import { Avatar, Badge, Button, Modal, Select, Tabs } from '@/shared/ui';

const days = Array.from({ length: 35 }, (_, index) => index < 3 || index > 33 ? null : index - 2);
const appointments = [{ day: 3, time: '10:00', title: 'Northstar discovery', owner: 'Alex Morgan', color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-200' }, { day: 7, time: '14:30', title: 'Orbit onboarding', owner: 'Sam Rivera', color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200' }, { day: 12, time: '09:00', title: 'Vertex demo', owner: 'Jordan Lee', color: 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200' }, { day: 18, time: '16:00', title: 'Pioneer review', owner: 'Alex Morgan', color: 'bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-200' }, { day: 24, time: '11:30', title: 'Lumon strategy', owner: 'Sam Rivera', color: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-200' }];

export function CalendarPage() {
  const [open, setOpen] = useState(false);
  const month = <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className="grid min-w-[50rem] grid-cols-7 border-b border-slate-200 text-center text-xs font-semibold uppercase text-slate-500 dark:border-slate-700">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => <div className="p-3" key={day}>{day}</div>)}</div><div className="grid min-w-[50rem] grid-cols-7">{days.map((day, index) => <div className="min-h-28 border-b border-r border-slate-200 p-2 dark:border-slate-700" key={index}>{day ? <><span className="text-xs font-medium">{day}</span>{appointments.filter((item) => item.day === day).map((item) => <button className={`mt-2 block w-full rounded-md p-2 text-left text-xs ${item.color}`} key={item.title} type="button"><strong className="block">{item.time}</strong>{item.title}</button>)}</> : null}</div>)}</div></div>;
  const schedule = (daysCount: number) => <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className={`grid min-w-[45rem] ${daysCount === 1 ? 'grid-cols-[5rem_1fr]' : 'grid-cols-[5rem_repeat(5,1fr)]'}`}>{Array.from({ length: 10 }, (_, hour) => <div className="contents" key={hour}><div className="border-b border-r border-slate-200 p-3 text-xs text-slate-500 dark:border-slate-700">{hour + 8}:00</div>{Array.from({ length: daysCount }, (_, day) => <div className="min-h-16 border-b border-r border-slate-200 p-1 dark:border-slate-700" key={day}>{hour === 2 && day === 1 ? <div className="rounded bg-indigo-100 p-2 text-xs text-indigo-800">Discovery call</div> : null}</div>)}</div>)}</div></div>;
  return <div className="grid gap-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-indigo-600">Scheduling</p><h1 className="text-3xl font-bold">Calendar</h1><p className="text-sm text-slate-500">Coordinate appointments, availability, and booking links.</p></div><Button onClick={() => setOpen(true)}><Plus size={16} />New appointment</Button></header><div className="grid gap-4 lg:grid-cols-[1fr_18rem]"><Tabs defaultValue="month" items={[{ label: 'Month', value: 'month', content: month }, { label: 'Week', value: 'week', content: schedule(5) }, { label: 'Day', value: 'day', content: schedule(1) }]} /><aside className="grid content-start gap-4"><section className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 font-semibold"><Users size={17} />Team availability</h2>{['Alex Morgan', 'Jordan Lee', 'Sam Rivera'].map((name, index) => <div className="mt-3 flex items-center gap-2" key={name}><Avatar alt={name} size="sm" /><span className="text-sm">{name}</span><Badge className="ml-auto" tone={index === 2 ? 'warning' : 'success'}>{index === 2 ? 'Busy' : 'Available'}</Badge></div>)}</section><section className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 font-semibold"><Link2 size={17} />Booking links</h2><p className="mt-2 text-sm text-slate-500">Discovery call · 30 min</p><Button className="mt-3 w-full" size="sm" variant="outline">Copy link</Button></section></aside></div><Modal onClose={() => setOpen(false)} open={open} title="New appointment"><div className="grid gap-4"><Select label="Contact" options={['Olivia Martin', 'Ethan Clark', 'Sophia Patel'].map((value) => ({ label: value, value }))} /><Select label="Assigned team member" options={['Alex Morgan', 'Jordan Lee', 'Sam Rivera'].map((value) => ({ label: value, value }))} /><label className="grid gap-1.5 text-sm font-medium">Date and time<input className="h-10 rounded-lg border border-slate-300 bg-transparent px-3 dark:border-slate-700" type="datetime-local" /></label><Button onClick={() => setOpen(false)}><CalendarDays size={16} />Schedule appointment</Button><p className="flex items-center gap-2 text-xs text-slate-500"><Clock size={14} />Mock scheduling only; no calendar event is created.</p></div></Modal></div>;
}

export default CalendarPage;
