import type { FeatureNames } from './naming.js';

export interface TemplateOptions {
  names: FeatureNames;
  tenantOwned: boolean;
  crud: boolean;
  eventProducing: boolean;
  queueJobs: boolean;
  frontend: boolean;
}

type Files = Record<string, string>;
const header = `// Generated by @repo/generators. Review and register before use.\n`;

export function backendTemplates(options: TemplateOptions): Files {
  const { names: n } = options;
  const tenantField = options.tenantOwned
    ? `  @Prop({ type: MongooseSchema.Types.ObjectId, required: true, index: true })\n  workspaceId!: Types.ObjectId;\n`
    : '';
  const tenantFilter = options.tenantOwned ? `workspaceId: new Types.ObjectId(workspaceId), ` : '';
  const workspaceArgument = options.tenantOwned ? 'workspaceId: string, ' : '';
  const workspaceValue = options.tenantOwned ? 'workspaceId: new Types.ObjectId(workspaceId), ' : '';
  const guard = options.tenantOwned ? `\n@RequireWorkspace()` : '';
  const contextImport = options.tenantOwned
    ? `import { WorkspaceContext } from '../../../common/decorators/workspace-context.decorator.js';\nimport { RequireWorkspace } from '../../../common/decorators/require-workspace.decorator.js';\nimport type { WorkspaceRequestContext } from '../../../common/types/workspace-context.js';\n`
    : '';
  const controllerContext = options.tenantOwned ? '@WorkspaceContext() context: WorkspaceRequestContext, ' : '';
  const serviceWorkspace = options.tenantOwned ? 'context.workspaceId, ' : '';
  const files: Files = {
    [`${n.kebab}.module.ts`]: `${header}import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';
import { ${n.pascal}Controller } from './controllers/${n.kebab}.controller.js';
import { ${n.pascal}Service } from './services/${n.kebab}.service.js';
import { ${n.singularPascal}, ${n.singularPascal}Schema } from './schemas/${n.singularKebab}.schema.js';
import { ${n.pascal}MongoRepository } from './repositories/${n.kebab}.mongo.repository.js';
import { ${n.pascal}RepositoryToken } from './repositories/${n.kebab}.repository.js';
import { ${n.singularPascal}Policy } from './policies/${n.singularKebab}.policy.js';
${options.queueJobs ? `import { ${n.pascal}Processor } from './jobs/${n.kebab}.processor.js';\n` : ''}
@Module({
  imports: [MongooseModule.forFeature([{ name: ${n.singularPascal}.name, schema: ${n.singularPascal}Schema }])],
  controllers: [${n.pascal}Controller],
  providers: [${n.pascal}Service, ${n.singularPascal}Policy, ${n.pascal}MongoRepository, { provide: ${n.pascal}RepositoryToken, useExisting: ${n.pascal}MongoRepository }${options.queueJobs ? `, ${n.pascal}Processor` : ''}],
  exports: [${n.pascal}Service, ${n.pascal}RepositoryToken],
})
export class ${n.pascal}Module {}
`,
    [`schemas/${n.singularKebab}.schema.ts`]: `${header}import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Types, type HydratedDocument${options.tenantOwned ? ', Schema as MongooseSchema' : ''} } from 'mongoose';

@Schema({ collection: '${n.kebab}', timestamps: true, versionKey: false })
export class ${n.singularPascal} {
  _id!: Types.ObjectId;
  createdAt!: Date;
  updatedAt!: Date;
${tenantField}  @Prop({ type: String, required: true, trim: true, maxlength: 200 })
  name!: string;
  @Prop({ type: Number, default: 0, min: 0 })
  version!: number;
  @Prop({ type: Date, default: null })
  deletedAt!: Date | null;
}
export type ${n.singularPascal}Document = HydratedDocument<${n.singularPascal}>;
export const ${n.singularPascal}Schema = SchemaFactory.createForClass(${n.singularPascal});
${options.tenantOwned ? `${n.singularPascal}Schema.index({ workspaceId: 1, name: 1, deletedAt: 1 });\n` : `${n.singularPascal}Schema.index({ name: 1, deletedAt: 1 });\n`}`,
    [`dto/${n.kebab}.dto.ts`]: `${header}import { IsInt, IsString, MaxLength, Min } from 'class-validator';
export class Create${n.singularPascal}Dto { @IsString() @MaxLength(200) name!: string; }
export class Update${n.singularPascal}Dto extends Create${n.singularPascal}Dto { @IsInt() @Min(0) version!: number; }
export class ${n.singularPascal}ResponseDto { id!: string; name!: string; version!: number; createdAt!: Date; updatedAt!: Date; }
`,
    [`mappers/${n.singularKebab}.mapper.ts`]: `${header}import type { ${n.singularPascal} } from '../schemas/${n.singularKebab}.schema.js';
import type { ${n.singularPascal}ResponseDto } from '../dto/${n.kebab}.dto.js';
export const map${n.singularPascal} = (value: ${n.singularPascal}): ${n.singularPascal}ResponseDto => ({ id: String(value._id), name: value.name, version: value.version, createdAt: value.createdAt, updatedAt: value.updatedAt });
`,
    [`repositories/${n.kebab}.repository.ts`]: `${header}import type { ${n.singularPascal} } from '../schemas/${n.singularKebab}.schema.js';
export const ${n.pascal}RepositoryToken = Symbol('${n.pascal}Repository');
export interface ${n.pascal}Repository { list(${workspaceArgument}limit: number): Promise<${n.singularPascal}[]>; get(${workspaceArgument}id: string): Promise<${n.singularPascal} | null>; create(${workspaceArgument}input: { name: string }): Promise<${n.singularPascal}>; update(${workspaceArgument}id: string, version: number, input: { name: string }): Promise<${n.singularPascal} | null>; remove(${workspaceArgument}id: string, version: number): Promise<${n.singularPascal} | null>; }
`,
    [`repositories/${n.kebab}.mongo.repository.ts`]: `${header}import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import type { ${n.pascal}Repository } from './${n.kebab}.repository.js';
import { ${n.singularPascal}, type ${n.singularPascal}Document } from '../schemas/${n.singularKebab}.schema.js';
@Injectable()
export class ${n.pascal}MongoRepository implements ${n.pascal}Repository {
  constructor(@InjectModel(${n.singularPascal}.name) private readonly model: Model<${n.singularPascal}Document>) {}
  list(${workspaceArgument}limit: number) { return this.model.find({ ${tenantFilter}deletedAt: null }).sort({ createdAt: -1 }).limit(limit).lean<${n.singularPascal}[]>().exec(); }
  get(${workspaceArgument}id: string) { return this.model.findOne({ _id: new Types.ObjectId(id), ${tenantFilter}deletedAt: null }).lean<${n.singularPascal}>().exec(); }
  async create(${workspaceArgument}input: { name: string }) { const value = await this.model.create({ ${workspaceValue}...input, version: 0, deletedAt: null }); return value.toObject(); }
  update(${workspaceArgument}id: string, version: number, input: { name: string }) { return this.model.findOneAndUpdate({ _id: new Types.ObjectId(id), ${tenantFilter}version, deletedAt: null }, { $set: input, $inc: { version: 1 } }, { new: true, runValidators: true }).lean<${n.singularPascal}>().exec(); }
  remove(${workspaceArgument}id: string, version: number) { return this.model.findOneAndUpdate({ _id: new Types.ObjectId(id), ${tenantFilter}version, deletedAt: null }, { $set: { deletedAt: new Date() }, $inc: { version: 1 } }, { new: true }).lean<${n.singularPascal}>().exec(); }
}
`,
    [`policies/${n.singularKebab}.policy.ts`]: `${header}import { BadRequestException, Injectable } from '@nestjs/common';
@Injectable() export class ${n.singularPascal}Policy { assertName(name: string) { if (!name.trim()) throw new BadRequestException('Name is required'); } }
`,
    [`services/${n.kebab}.service.ts`]: `${header}import { ${options.crud ? 'ConflictException, ' : ''}Inject, Injectable, NotFoundException } from '@nestjs/common';
import { ${n.pascal}RepositoryToken, type ${n.pascal}Repository } from '../repositories/${n.kebab}.repository.js';
import { map${n.singularPascal} } from '../mappers/${n.singularKebab}.mapper.js';
import { ${n.singularPascal}Policy } from '../policies/${n.singularKebab}.policy.js';
@Injectable()
export class ${n.pascal}Service {
  constructor(@Inject(${n.pascal}RepositoryToken) private readonly repository: ${n.pascal}Repository, private readonly policy: ${n.singularPascal}Policy) {}
  async list(${workspaceArgument}limit = 50) { return (await this.repository.list(${options.tenantOwned ? 'workspaceId, ' : ''}limit)).map(map${n.singularPascal}); }
  async get(${workspaceArgument}id: string) { const value = await this.repository.get(${options.tenantOwned ? 'workspaceId, ' : ''}id); if (!value) throw new NotFoundException('${n.singularPascal} not found'); return map${n.singularPascal}(value); }
${options.crud ? `  async create(${workspaceArgument}input: { name: string }) { this.policy.assertName(input.name); return map${n.singularPascal}(await this.repository.create(${options.tenantOwned ? 'workspaceId, ' : ''}input)); }
  async update(${workspaceArgument}id: string, version: number, input: { name: string }) { this.policy.assertName(input.name); const value = await this.repository.update(${options.tenantOwned ? 'workspaceId, ' : ''}id, version, input); if (!value) throw new ConflictException('Resource changed or no longer exists'); return map${n.singularPascal}(value); }
  async remove(${workspaceArgument}id: string, version: number) { const value = await this.repository.remove(${options.tenantOwned ? 'workspaceId, ' : ''}id, version); if (!value) throw new ConflictException('Resource changed or no longer exists'); return map${n.singularPascal}(value); }
` : ''}}
`,
    [`controllers/${n.kebab}.controller.ts`]: `${header}import { ${options.crud ? 'Body, Delete, Patch, Post, ' : ''}Controller, Get, Param, Query } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
${contextImport}import { ParseMongoIdPipe } from '../../../common/pipes/parse-mongo-id.pipe.js';
${options.crud ? `import { Create${n.singularPascal}Dto, Update${n.singularPascal}Dto } from '../dto/${n.kebab}.dto.js';\n` : ''}import { ${n.pascal}Service } from '../services/${n.kebab}.service.js';
@ApiTags('${n.kebab}')
@Controller('${n.kebab}')${guard}
export class ${n.pascal}Controller {
  constructor(private readonly service: ${n.pascal}Service) {}
  @Get() @ApiOperation({ summary: 'List ${n.kebab}' }) list(${controllerContext}@Query('limit') limit?: string) { return this.service.list(${serviceWorkspace}limit ? Number(limit) : 50); }
  @Get(':id') get(${controllerContext}@Param('id', ParseMongoIdPipe) id: string) { return this.service.get(${serviceWorkspace}id); }
${options.crud ? `  @Post() create(${controllerContext}@Body() dto: Create${n.singularPascal}Dto) { return this.service.create(${serviceWorkspace}dto); }
  @Patch(':id') update(${controllerContext}@Param('id', ParseMongoIdPipe) id: string, @Body() dto: Update${n.singularPascal}Dto) { return this.service.update(${serviceWorkspace}id, dto.version, dto); }
  @Delete(':id') remove(${controllerContext}@Param('id', ParseMongoIdPipe) id: string, @Query('version') version: string) { return this.service.remove(${serviceWorkspace}id, Number(version)); }
` : ''}}
`,
    [`services/${n.kebab}.service.spec.ts`]: `${header}import { describe, expect, it, vi } from 'vitest';
import { ${n.pascal}Service } from './${n.kebab}.service.js';
describe('${n.pascal}Service', () => { it('maps repository results', async () => { const repository = { list: vi.fn().mockResolvedValue([]) }; const service = new ${n.pascal}Service(repository as never, { assertName: vi.fn() } as never); await expect(service.list(${options.tenantOwned ? `'507f1f77bcf86cd799439011', ` : ''}10)).resolves.toEqual([]); }); });
`,
    ['index.ts']: `${header}export { ${n.pascal}Module } from './${n.kebab}.module.js';
export { ${n.pascal}Service } from './services/${n.kebab}.service.js';
export type { ${n.pascal}Repository } from './repositories/${n.kebab}.repository.js';
`,
  };
  if (options.eventProducing) files[`events/${n.singularKebab}.events.ts`] = `${header}export interface ${n.singularPascal}ChangedEvent { type: '${n.singularKebab}.changed'; ${options.tenantOwned ? 'workspaceId: string; ' : ''}entityId: string; occurredAt: string; }\n`;
  if (options.queueJobs) files[`jobs/${n.kebab}.processor.ts`] = `${header}import { Injectable } from '@nestjs/common';\n@Injectable() export class ${n.pascal}Processor { async process(payload: { entityId: string }): Promise<void> { if (!payload.entityId) throw new Error('entityId is required'); } }\n`;
  return files;
}

export function frontendTemplates(options: TemplateOptions): Files {
  const n = options.names;
  if (!options.frontend) return {};
  return {
    [`types/${n.kebab}.types.ts`]: `${header}export interface ${n.singularPascal} { id: string; name: string; version: number; createdAt: string; updatedAt: string; }\nexport interface ${n.singularPascal}Input { name: string; version?: number; }\n`,
    [`schemas/${n.singularKebab}.schema.ts`]: `${header}import { z } from 'zod';\nexport const ${n.singularCamel}Schema = z.object({ name: z.string().trim().min(1).max(200) });\n`,
    [`api/${n.kebab}.api.ts`]: `${header}import { appConfig } from '@/app/config/app.config';\nimport type { ${n.singularPascal}, ${n.singularPascal}Input } from '../types/${n.kebab}.types';\nconst request = async <T>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(\`${'${appConfig.apiUrl}'}${'${path}'}\`, { ...init, credentials: 'include', headers: { 'content-type': 'application/json', ...init?.headers } }); if (!response.ok) throw new Error(\`Request failed: ${'${response.status}'}\`); return response.json() as Promise<T>; };\nexport const list${n.pascal} = () => request<${n.singularPascal}[]>('/${n.kebab}');\nexport const create${n.singularPascal} = (input: ${n.singularPascal}Input) => request<${n.singularPascal}>('/${n.kebab}', { method: 'POST', body: JSON.stringify(input) });\n`,
    [`hooks/use-${n.kebab}.ts`]: `${header}import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';\nimport { create${n.singularPascal}, list${n.pascal} } from '../api/${n.kebab}.api';\nexport const ${n.camel}Keys = { all: ['${n.kebab}'] as const };\nexport const use${n.pascal} = () => useQuery({ queryKey: ${n.camel}Keys.all, queryFn: list${n.pascal} });\nexport const useCreate${n.singularPascal} = () => { const client = useQueryClient(); return useMutation({ mutationFn: create${n.singularPascal}, onSuccess: () => client.invalidateQueries({ queryKey: ${n.camel}Keys.all }) }); };\n`,
    [`components/${n.singularPascal}Form.tsx`]: `${header}import { useState, type FormEvent } from 'react';\nimport { Button, Input } from '@/shared/ui';\nexport function ${n.singularPascal}Form({ onSubmit }: { onSubmit: (name: string) => void }) { const [name, setName] = useState(''); return <form onSubmit={(event: FormEvent) => { event.preventDefault(); if (name.trim()) onSubmit(name.trim()); }}><Input label="Name" onChange={(event) => setName(event.target.value)} value={name} /><Button type="submit">Create</Button></form>; }\n`,
    [`pages/${n.pascal}Page.tsx`]: `${header}import { EmptyState, ErrorState, Skeleton } from '@/shared/ui';\nimport { ${n.singularPascal}Form } from '../components/${n.singularPascal}Form';\nimport { useCreate${n.singularPascal}, use${n.pascal} } from '../hooks/use-${n.kebab}';\nexport function ${n.pascal}Page() { const query = use${n.pascal}(); const create = useCreate${n.singularPascal}(); if (query.isLoading) return <Skeleton className="h-40" />; if (query.isError) return <ErrorState title="${n.pascal} unavailable" onRetry={() => void query.refetch()} />; return <div><h1>${n.pascal}</h1><${n.singularPascal}Form onSubmit={(name) => create.mutate({ name })} />{query.data?.length ? <ul>{query.data.map((item) => <li key={item.id}>{item.name}</li>)}</ul> : <EmptyState title="No ${n.kebab} yet" />}</div>; }\nexport default ${n.pascal}Page;\n`,
    [`schemas/${n.singularKebab}.schema.test.ts`]: `${header}import { describe, expect, it } from 'vitest';\nimport { ${n.singularCamel}Schema } from './${n.singularKebab}.schema';\ndescribe('${n.singularCamel}Schema', () => { it('accepts a valid name and rejects empty input', () => { expect(${n.singularCamel}Schema.safeParse({ name: 'Example' }).success).toBe(true); expect(${n.singularCamel}Schema.safeParse({ name: '' }).success).toBe(false); }); });\n`,
    ['index.ts']: `${header}export { ${n.pascal}Page } from './pages/${n.pascal}Page';\nexport type { ${n.singularPascal}, ${n.singularPascal}Input } from './types/${n.kebab}.types';\n`,
  };
}
