import{Prop,Schema,SchemaFactory}from'@nestjs/mongoose';import{HydratedDocument,Schema as MongooseSchema,Types}from'mongoose';import{PROVIDERS}from'../types/provider-adapter.js';
@Schema({collection:'integration_connections',timestamps:true,versionKey:false})export class IntegrationConnection{_id!:Types.ObjectId;createdAt!:Date;updatedAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:String,enum:PROVIDERS,required:true})provider!:string;@Prop({type:String,required:true})name!:string;@Prop({type:String,enum:['pending','active','error','disabled','needs_attention'],default:'pending'})status!:string;@Prop({type:MongooseSchema.Types.Mixed,default:{}})publicMetadata!:Record<string,unknown>;@Prop({type:Date,default:null})lastValidatedAt!:Date|null;@Prop({type:Date,default:null})lastSyncAt!:Date|null;@Prop({type:String,default:null})lastErrorCode!:string|null;@Prop({type:String,default:null})lastFailureMessage!:string|null;@Prop({type:Date,default:null})lastFailureAt!:Date|null;@Prop({type:MongooseSchema.Types.ObjectId,required:true})createdBy!:Types.ObjectId}
export type IntegrationConnectionDocument=HydratedDocument<IntegrationConnection>;export const IntegrationConnectionSchema=SchemaFactory.createForClass(IntegrationConnection);IntegrationConnectionSchema.index({workspaceId:1,provider:1,status:1});
@Schema({collection:'integration_credentials',timestamps:true,versionKey:false})export class IntegrationCredential{@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})connectionId!:Types.ObjectId;@Prop({type:String,required:true,select:false})encryptedPayload!:string;@Prop({type:Number,default:1})keyVersion!:number;@Prop({type:Date,default:null})expiresAt!:Date|null}
export const IntegrationCredentialSchema=SchemaFactory.createForClass(IntegrationCredential);IntegrationCredentialSchema.index({workspaceId:1,connectionId:1},{unique:true});
@Schema({collection:'integration_webhook_events',timestamps:true,versionKey:false})export class IntegrationWebhookEvent{_id!:Types.ObjectId;createdAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})connectionId!:Types.ObjectId;@Prop({type:String,required:true})provider!:string;@Prop({type:String,required:true})providerEventId!:string;@Prop({type:String,required:true})eventType!:string;@Prop({type:Date,required:true})providerTimestamp!:Date;@Prop({type:String,required:true})payloadHash!:string;@Prop({type:MongooseSchema.Types.Mixed,required:true})payload!:Record<string,unknown>;@Prop({type:String,enum:['queued','processing','processed','failed','dead_letter'],default:'queued'})status!:string;@Prop({type:Number,default:0})attemptCount!:number;@Prop({type:String,default:null})failureCode!:string|null}
export const IntegrationWebhookEventSchema=SchemaFactory.createForClass(IntegrationWebhookEvent);IntegrationWebhookEventSchema.index({workspaceId:1,connectionId:1,providerEventId:1},{unique:true});IntegrationWebhookEventSchema.index({workspaceId:1,status:1,createdAt:1});
@Schema({collection:'integration_webhook_deliveries',timestamps:true,versionKey:false})export class IntegrationWebhookDelivery{@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})webhookEventId!:Types.ObjectId;@Prop({type:Number,required:true})attempt!:number;@Prop({type:String,required:true})status!:string;@Prop({type:Number,default:null})responseStatus!:number|null;@Prop({type:String,default:null})errorCode!:string|null;@Prop({type:Number,default:0})durationMs!:number}
export const IntegrationWebhookDeliverySchema=SchemaFactory.createForClass(IntegrationWebhookDelivery);IntegrationWebhookDeliverySchema.index({workspaceId:1,webhookEventId:1,attempt:1},{unique:true});
@Schema({collection:'integration_sync_jobs',timestamps:true,versionKey:false})export class IntegrationSyncJob{@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})connectionId!:Types.ObjectId;@Prop({type:String,required:true})resource!:string;@Prop({type:String,enum:['queued','running','completed','partial','failed','dead_letter'],default:'queued'})status!:string;@Prop({type:String,required:true})idempotencyKey!:string;@Prop({type:String,default:null})cursor!:string|null;@Prop({type:Number,default:0})recordsProcessed!:number;@Prop({type:Number,default:0})recordsFailed!:number;@Prop({type:Number,default:0})attemptCount!:number;@Prop({type:String,default:null})failureCode!:string|null;@Prop({type:String,default:null})failureMessage!:string|null}
export const IntegrationSyncJobSchema=SchemaFactory.createForClass(IntegrationSyncJob);IntegrationSyncJobSchema.index({workspaceId:1,idempotencyKey:1},{unique:true});
@Schema({collection:'integration_provider_health',timestamps:true,versionKey:false})export class IntegrationProviderHealth{@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})connectionId!:Types.ObjectId;@Prop({type:Boolean,required:true})healthy!:boolean;@Prop({type:String,default:null})message!:string|null;@Prop({type:Date,required:true})checkedAt!:Date}
export const IntegrationProviderHealthSchema=SchemaFactory.createForClass(IntegrationProviderHealth);IntegrationProviderHealthSchema.index({workspaceId:1,connectionId:1,checkedAt:-1});
@Schema({collection:'integration_conversion_deliveries',timestamps:true,versionKey:false})export class IntegrationConversionDelivery{_id!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})connectionId!:Types.ObjectId;@Prop({type:String,required:true})eventId!:string;@Prop({type:String,required:true})eventName!:string;@Prop({type:String,required:true})pixelId!:string;@Prop({type:String,enum:['queued','processing','delivered','failed','dead_letter'],default:'queued'})status!:string;@Prop({type:Number,default:0})attemptCount!:number;@Prop({type:String,required:true})payloadHash!:string;@Prop({type:Number,default:null})responseStatus!:number|null;@Prop({type:MongooseSchema.Types.Mixed,default:null})responseSummary!:Record<string,unknown>|null;@Prop({type:String,default:null})errorCode!:string|null;@Prop({type:Date,default:null})deliveredAt!:Date|null}
export const IntegrationConversionDeliverySchema=SchemaFactory.createForClass(IntegrationConversionDelivery);IntegrationConversionDeliverySchema.index({workspaceId:1,connectionId:1,eventId:1},{unique:true});IntegrationConversionDeliverySchema.index({workspaceId:1,status:1,createdAt:1});
