import { BarChart3, CalendarClock, Mail, MessageCircle, Plus, Send, Smartphone, Users } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Input, MetricCard, Modal, Select, Table, Tabs, Textarea, type TableColumn } from '@/shared/ui';

interface Campaign { id: string; name: string; channel: string; audience: string; status: 'active' | 'draft' | 'scheduled' | 'completed'; sent: number; rate: string; scheduled: string }
const seed: Campaign[] = [
  { id: 'c1', name: 'Summer product launch', channel: 'Email', audience: 'Marketing qualified leads', status: 'active', sent: 12840, rate: '38.4%', scheduled: 'Jul 24, 09:00' },
  { id: 'c2', name: 'Demo reminder', channel: 'WhatsApp', audience: 'Upcoming appointments', status: 'scheduled', sent: 0, rate: '—', scheduled: 'Jul 25, 08:30' },
  { id: 'c3', name: 'Flash offer', channel: 'SMS', audience: 'Active customers', status: 'completed', sent: 8240, rate: '12.8%', scheduled: 'Jul 18, 12:00' },
  { id: 'c4', name: 'Customer stories', channel: 'Social', audience: 'LinkedIn followers', status: 'draft', sent: 0, rate: '—', scheduled: 'Not scheduled' },
];

export function CampaignsPage() {
  const [campaigns, setCampaigns] = useState(seed); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [channel, setChannel] = useState('Email');
  const columns: TableColumn<Campaign>[] = [{ key: 'name', header: 'Campaign', render: (row) => <div><strong>{row.name}</strong><p className="text-xs text-slate-500">{row.audience}</p></div> }, { key: 'channel', header: 'Channel', render: (row) => <Badge tone="neutral">{row.channel}</Badge> }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'active' ? 'success' : row.status === 'scheduled' ? 'primary' : row.status === 'draft' ? 'warning' : 'neutral'}>{row.status}</Badge> }, { key: 'schedule', header: 'Schedule', render: (row) => row.scheduled }, { key: 'sent', header: 'Sent', align: 'right', render: (row) => row.sent.toLocaleString() }, { key: 'rate', header: 'Conversion', align: 'right', render: (row) => row.rate }];
  const templates = <div className="grid gap-4 md:grid-cols-3">{['Product announcement', 'Appointment reminder', 'Limited-time offer', 'Newsletter', 'Customer win-back', 'Event invitation'].map((template, index) => <article className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900" key={template}><span className="grid size-10 place-items-center rounded-lg bg-indigo-50 text-indigo-600 dark:bg-indigo-950">{index % 3 === 0 ? <Mail /> : index % 3 === 1 ? <MessageCircle /> : <Smartphone />}</span><h3 className="mt-4 font-semibold">{template}</h3><p className="mt-1 text-sm text-slate-500">Responsive starter content with editable audience and schedule.</p><Button className="mt-4" size="sm" variant="outline">Use template</Button></article>)}</div>;
  return <div className="grid gap-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-indigo-600">Audience engagement</p><h1 className="text-3xl font-bold">Campaigns</h1><p className="text-sm text-slate-500">Plan coordinated email, SMS, WhatsApp, and social outreach.</p></div><Button onClick={() => setOpen(true)}><Plus size={16} />Create campaign</Button></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard description="Across every channel" icon={<Send />} label="Messages sent" value="42,680" /><MetricCard change={8.2} description="Unique recipients" icon={<Users />} label="Audience reached" value="31,420" /><MetricCard description="Blended engagement" icon={<BarChart3 />} label="Conversion rate" value="18.7%" /><MetricCard description="Next seven days" icon={<CalendarClock />} label="Scheduled" value="6" /></div><Tabs defaultValue="campaigns" items={[{ label: 'Campaigns', value: 'campaigns', content: <Table columns={columns} getRowKey={(row) => row.id} rows={campaigns} /> }, { label: 'Templates', value: 'templates', content: templates }, { label: 'Reports', value: 'reports', content: <div className="grid gap-4 md:grid-cols-3"><MetricCard label="Email open rate" value="41.2%" /><MetricCard label="SMS click rate" value="16.4%" /><MetricCard label="WhatsApp replies" value="1,284" /></div> }]} /><Modal onClose={() => setOpen(false)} open={open} title="Create campaign"><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); if (!name.trim()) return; setCampaigns((current) => [{ id: crypto.randomUUID(), name, channel, audience: 'All contacts', status: 'draft', sent: 0, rate: '—', scheduled: 'Not scheduled' }, ...current]); setName(''); setOpen(false); }}><Input label="Campaign name" onChange={(event) => setName(event.target.value)} value={name} /><Select label="Channel" onChange={(event) => setChannel(event.target.value)} options={['Email', 'SMS', 'WhatsApp', 'Social'].map((value) => ({ label: value, value }))} value={channel} /><Select label="Audience" options={['All contacts', 'Marketing qualified leads', 'Active customers'].map((value) => ({ label: value, value }))} /><Input label="Schedule" type="datetime-local" /><Textarea label="Message" placeholder="Compose campaign content…" /><Button disabled={!name.trim()} type="submit">Save draft</Button></form></Modal></div>;
}

export default CampaignsPage;
