import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { HighLevelContactsService } from './highlevel-contacts.service.js';
import { mapHighLevelAppointment,mapHighLevelContact,mapHighLevelOpportunity } from './highlevel-mappers.js';
import { HighLevelOAuthService } from './highlevel-oauth.service.js';
import { HighLevelWebhookService } from './highlevel-webhook.service.js';

const context={workspaceId:'workspace-a',connectionId:'connection-a',provider:'highlevel',credentials:{accessToken:'access',refreshToken:'refresh',locationId:'location-a'}} as never;
describe('HighLevel integration',()=>{
 beforeEach(()=>{process.env.HIGHLEVEL_CLIENT_ID='client';process.env.HIGHLEVEL_CLIENT_SECRET='secret';process.env.HIGHLEVEL_REDIRECT_URI='https://app.test/callback';});
 afterEach(()=>{vi.unstubAllGlobals();delete process.env.HIGHLEVEL_CLIENT_ID;delete process.env.HIGHLEVEL_CLIENT_SECRET;delete process.env.HIGHLEVEL_REDIRECT_URI;});
 it('maps OAuth token and location context',async()=>{const request=vi.fn().mockResolvedValue({ok:true,json:vi.fn().mockResolvedValue({access_token:'new-access',refresh_token:'new-refresh',expires_in:3600,locationId:'location-a'})});vi.stubGlobal('fetch',request);const value=await new HighLevelOAuthService().exchange('code');expect(value).toMatchObject({accessToken:'new-access',refreshToken:'new-refresh',locationId:'location-a',accountId:'location-a'});expect(String(request.mock.calls[0][1].body)).not.toContain('new-access');});
 it('refreshes with the refresh grant and preserves context',async()=>{const request=vi.fn().mockResolvedValue({ok:true,json:vi.fn().mockResolvedValue({access_token:'rotated',expires_in:3600})});vi.stubGlobal('fetch',request);const value=await new HighLevelOAuthService().refresh(context.credentials);expect(value).toMatchObject({accessToken:'rotated',refreshToken:'refresh',locationId:'location-a'});expect(String(request.mock.calls[0][1].body)).toContain('grant_type=refresh_token');});
 it('maps contacts, opportunities, appointments, and unknown contact fields',()=>{const contact=mapHighLevelContact(context,{id:'contact-1',email:'lead@example.com',favoriteColor:'blue'}),opportunity=mapHighLevelOpportunity({id:'opp-1',contactId:'contact-1',pipelineId:'pipe-1',monetaryValue:250}),appointment=mapHighLevelAppointment({id:'appt-1',contactId:'contact-1',calendarId:'cal-1',appointmentStatus:'confirmed'});expect(contact).toMatchObject({workspaceId:'workspace-a',externalLeadId:'contact-1',fields:{favoriteColor:'blue',locationId:'location-a'}});expect(opportunity).toMatchObject({externalId:'opp-1',contactId:'contact-1',monetaryValue:250});expect(appointment).toMatchObject({externalId:'appt-1',calendarId:'cal-1',status:'confirmed'});});
 it('maps webhook identity deterministically and ignores non-contact events',async()=>{const ingestion={ingest:vi.fn()},service=new HighLevelWebhookService(ingestion as never),body=Buffer.from(JSON.stringify({type:'OpportunityCreate',id:'opp-1',timestamp:'2026-01-01T00:00:00Z'}));expect(service.envelopes(body)[0]).toEqual(service.envelopes(body)[0]);await service.process({eventType:'OpportunityCreate',payload:{id:'opp-1'}} as never,context);expect(ingestion.ingest).not.toHaveBeenCalled();});
 it('relies on unified ingestion for duplicate contacts and never invokes outbound upsert during inbound sync',async()=>{const api={request:vi.fn().mockResolvedValue({contacts:[{id:'contact-1',email:'lead@example.com'}]})},ingestion={ingest:vi.fn().mockResolvedValueOnce({created:true}).mockResolvedValueOnce({created:false,duplicate:true})},service=new HighLevelContactsService(api as never,ingestion as never);const outbound=vi.spyOn(service,'upsert');await service.list(context,undefined,25);await service.list(context,undefined,25);expect(ingestion.ingest).toHaveBeenCalledTimes(2);expect(ingestion.ingest.mock.calls[0][0]).toMatchObject({workspaceId:'workspace-a',externalLeadId:'contact-1'});expect(outbound).not.toHaveBeenCalled();});
 it('returns successful records together with sanitized partial-sync failures',async()=>{const api={request:vi.fn().mockResolvedValue({contacts:[{id:'good'},{id:'bad'}]})},ingestion={ingest:vi.fn().mockResolvedValueOnce({created:true}).mockRejectedValueOnce(new Error('private database detail'))},result=await new HighLevelContactsService(api as never,ingestion as never).list(context,undefined,25);expect(result.records).toHaveLength(1);expect(result.failures).toEqual([{externalId:'bad',code:'Error',message:'Contact could not be ingested'}]);expect(JSON.stringify(result)).not.toContain('private database detail');});
 it('rejects malformed webhook payloads with a structured non-retryable error',()=>{expect(()=>new HighLevelWebhookService({} as never).envelopes(Buffer.from('{bad json'))).toThrow('Malformed HighLevel webhook payload');});
});
