import { Injectable } from '@nestjs/common';
import type { ProviderCredentials } from '../../types/provider-adapter.js';
import { HIGHLEVEL_AUTHORIZE_URL,HIGHLEVEL_OAUTH_SCOPES,HIGHLEVEL_TOKEN_URL } from './highlevel.constants.js';
import { HighLevelError } from './highlevel.errors.js';
import type { HighLevelTokenResponse } from './highlevel.types.js';
@Injectable() export class HighLevelOAuthService{
 authorizationUrl(state:string,redirectUri:string){const clientId=this.required('HIGHLEVEL_CLIENT_ID'),configured=this.required('HIGHLEVEL_REDIRECT_URI');if(redirectUri!==configured)throw new HighLevelError('HIGHLEVEL_REDIRECT_URI_MISMATCH','OAuth redirect URI does not match configured HighLevel redirect URI');const url=new URL(HIGHLEVEL_AUTHORIZE_URL);url.search=new URLSearchParams({response_type:'code',client_id:clientId,redirect_uri:configured,scope:HIGHLEVEL_OAUTH_SCOPES,state}).toString();return url.toString()}
 exchange(code:string):Promise<ProviderCredentials>{return this.token({grant_type:'authorization_code',code,client_id:this.required('HIGHLEVEL_CLIENT_ID'),client_secret:this.required('HIGHLEVEL_CLIENT_SECRET'),redirect_uri:this.required('HIGHLEVEL_REDIRECT_URI')})}
 refresh(credentials:ProviderCredentials):Promise<ProviderCredentials>{if(!credentials.refreshToken)throw new HighLevelError('HIGHLEVEL_REFRESH_TOKEN_MISSING','Reconnect HighLevel because no refresh token is available');return this.token({grant_type:'refresh_token',refresh_token:credentials.refreshToken,client_id:this.required('HIGHLEVEL_CLIENT_ID'),client_secret:this.required('HIGHLEVEL_CLIENT_SECRET')},credentials)}
 private async token(fields:Record<string,string>,previous:ProviderCredentials={}):Promise<ProviderCredentials>{const response=await fetch(HIGHLEVEL_TOKEN_URL,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});if(!response.ok)throw new HighLevelError(`HIGHLEVEL_OAUTH_${response.status}`,'HighLevel authorization failed; reconnect the integration',response.status>=500,response.status);const value=await response.json()as HighLevelTokenResponse;if(!value.access_token)throw new HighLevelError('HIGHLEVEL_TOKEN_EXCHANGE_FAILED','HighLevel did not return an access token');const refreshToken=value.refresh_token??previous.refreshToken,locationId=value.locationId??previous.locationId,companyId=value.companyId??previous.companyId,webhookPublicKey=process.env.HIGHLEVEL_WEBHOOK_PUBLIC_KEY;return{...previous,accessToken:value.access_token,expiresAt:new Date(Date.now()+(value.expires_in??86400)*1000).toISOString(),...(refreshToken?{refreshToken}:{}),...(locationId?{locationId,accountId:locationId}:{}),...(companyId?{companyId}:{}),...(webhookPublicKey?{webhookPublicKey}:{})}}
 private required(name:string){const value=process.env[name];if(!value)throw new HighLevelError('HIGHLEVEL_CONFIG_MISSING',`${name} is not configured`);return value}
}
