import { Injectable } from '@nestjs/common';
import { ExternalLeadIngestionService } from '../../../leads/services/external-lead-ingestion.service.js';
import type { ProviderConnectionContext,SyncResult } from '../../types/provider-adapter.js';
import { HighLevelApiClient } from './highlevel-api.client.js';import { HighLevelError } from './highlevel.errors.js';import { mapHighLevelContact } from './highlevel-mappers.js';import type { HighLevelContact,HighLevelPage } from './highlevel.types.js';
@Injectable() export class HighLevelContactsService{constructor(private readonly api:HighLevelApiClient,private readonly ingestion:ExternalLeadIngestionService){}
 async list(context:ProviderConnectionContext,cursor:string|undefined,limit:number):Promise<SyncResult>{const token=this.token(context),locationId=this.location(context),page=await this.api.request<HighLevelPage<HighLevelContact>>(token,'/contacts/',{query:{locationId,limit,startAfter:cursor}}),contacts=page.contacts??[],records:Record<string,unknown>[]=[],failures:Array<{externalId?:string;code:string;message:string}>=[];for(const contact of contacts)try{await this.ingestion.ingest(mapHighLevelContact(context,contact));records.push(contact)}catch(error){failures.push({externalId:contact.id,code:error instanceof Error?error.name:'INGESTION_FAILED',message:'Contact could not be ingested'})}const nextCursor=this.cursor(page);return{records,...(nextCursor?{nextCursor}:{}),...(failures.length?{failures}:{})}}
 async get(context:ProviderConnectionContext,id:string){return this.api.request<{contact:HighLevelContact}>(this.token(context),`/contacts/${encodeURIComponent(id)}`)}
 async upsert(context:ProviderConnectionContext,contact:Record<string,unknown>){return this.api.request(this.token(context),'/contacts/upsert',{method:'POST',body:{...contact,locationId:this.location(context)}})}
 private token(c:ProviderConnectionContext){if(!c.credentials.accessToken)throw new HighLevelError('HIGHLEVEL_TOKEN_MISSING','HighLevel access token is unavailable');return c.credentials.accessToken}private location(c:ProviderConnectionContext){const id=c.credentials.locationId??c.credentials.accountId;if(!id)throw new HighLevelError('HIGHLEVEL_LOCATION_MISSING','Select a HighLevel location before synchronizing');return id}private cursor(page:HighLevelPage<unknown>){const url=page.meta?.nextPageUrl;return url?new URL(url).searchParams.get('startAfter')??undefined:undefined}}
