import{Injectable}from'@nestjs/common';import{createPublicKey,verify}from'node:crypto';import type{IntegrationProviderAdapter,ProviderConnectionContext,ProviderCredentials,ProviderHealth,ProviderResource,ProviderResourceSelection,ProviderSelectionResult,SyncRequest,SyncResult,WebhookEnvelope}from'../../types/provider-adapter.js';import{HighLevelApiClient}from'./highlevel-api.client.js';import{HighLevelCalendarService}from'./highlevel-calendar.service.js';import{HighLevelContactsService}from'./highlevel-contacts.service.js';import{HighLevelError}from'./highlevel.errors.js';import{HighLevelOAuthService}from'./highlevel-oauth.service.js';import{HighLevelOpportunitiesService}from'./highlevel-opportunities.service.js';import{HighLevelPipelinesService}from'./highlevel-pipelines.service.js';import{HighLevelWebhookService}from'./highlevel-webhook.service.js';
@Injectable()export class HighLevelProviderAdapter implements IntegrationProviderAdapter{readonly provider='highlevel' as const;constructor(private readonly oauth:HighLevelOAuthService,private readonly api:HighLevelApiClient,private readonly contacts:HighLevelContactsService,private readonly opportunities:HighLevelOpportunitiesService,private readonly pipelines:HighLevelPipelinesService,private readonly calendar:HighLevelCalendarService,private readonly webhooks:HighLevelWebhookService){}
 authorizationUrl(input:{state:string;redirectUri:string}){return this.oauth.authorizationUrl(input.state,input.redirectUri)}connect(input:Record<string,string>){const code=input.code;if(!code)throw new HighLevelError('HIGHLEVEL_AUTHORIZATION_CODE_MISSING','HighLevel authorization code is required');return this.oauth.exchange(code)}refreshCredentials(c:ProviderConnectionContext){return this.oauth.refresh(c.credentials)}disconnect(){return Promise.resolve()}
 async validateConnection(c:ProviderConnectionContext){try{const id=c.credentials.locationId??c.credentials.accountId;if(!id||!c.credentials.accessToken)return false;await this.api.request(c.credentials.accessToken,`/locations/${encodeURIComponent(id)}`);return true}catch{return false}}
 async discoverResources(c:ProviderConnectionContext):Promise<ProviderResource[]>{const token=this.token(c),known=c.credentials.locationId??c.credentials.accountId;if(known){const value=await this.api.request<{location?:{id:string;name?:string}}>(token,`/locations/${encodeURIComponent(known)}`),location=value.location??{id:known,name:known};return[{type:'location',id:location.id,name:location.name??location.id}]}const result=await this.api.request<{locations?:Array<{id:string;name?:string}>}>(token,'/locations/search',{query:{...(c.credentials.companyId?{companyId:c.credentials.companyId}:{})}});return(result.locations??[]).map(location=>({type:'location',id:location.id,name:location.name??location.id}))}
 selectResources(c:ProviderConnectionContext,selection:ProviderResourceSelection):Promise<ProviderSelectionResult>{const ids=selection.locationIds??[],locationId=ids[0];if(ids.length!==1||!locationId)throw new HighLevelError('HIGHLEVEL_LOCATION_SELECTION_INVALID','Select exactly one HighLevel location per connection');const credentials:ProviderCredentials={...c.credentials,locationId,accountId:locationId,selectedResourceIds:{...(c.credentials.selectedResourceIds??{}),locations:ids}};return Promise.resolve({credentials,publicMetadata:{selectedResources:{locationIds:ids}}})}
 sync(c:ProviderConnectionContext,r:SyncRequest):Promise<SyncResult>{if(r.resource==='contacts')return this.contacts.list(c,r.cursor,r.limit);if(r.resource==='opportunities')return this.opportunities.list(c,r.cursor,r.limit);if(r.resource==='appointments')return this.calendar.appointments(c,r.cursor,r.limit);if(r.resource==='pipelines')return this.pipelines.list(c).then(value=>({records:this.records(value,'pipelines')}));if(r.resource==='calendars')return this.calendar.calendars(c).then(value=>({records:this.records(value,'calendars')}));throw new HighLevelError('HIGHLEVEL_RESOURCE_UNSUPPORTED',`HighLevel resource ${r.resource} is not supported`)}
 subscribeWebhooks(){return Promise.resolve()}handleWebhook(raw:Buffer):Promise<WebhookEnvelope>{return Promise.resolve(this.webhooks.envelopes(raw)[0]!)}handleWebhooks(raw:Buffer){return Promise.resolve(this.webhooks.envelopes(raw))}
 verifyWebhook(raw:Buffer,headers:Record<string,string|undefined>,publicKey:string){const signature=headers['x-ghl-signature'];if(!signature||!publicKey)return false;try{return verify(null,raw,createPublicKey(this.pem(publicKey)),Buffer.from(signature,'base64'))}catch{return false}}
 async healthCheck(c:ProviderConnectionContext):Promise<ProviderHealth>{const healthy=await this.validateConnection(c);return{healthy,...(!healthy?{message:'HighLevel credentials are invalid or require reconnection'}:{}),checkedAt:new Date()}}
 private token(c:ProviderConnectionContext){if(!c.credentials.accessToken)throw new HighLevelError('HIGHLEVEL_TOKEN_MISSING','HighLevel access token is unavailable');return c.credentials.accessToken}private records(value:unknown,key:string){if(typeof value!=='object'||value===null)return[];const records=(value as Record<string,unknown>)[key];return Array.isArray(records)?records.filter((v):v is Record<string,unknown>=>typeof v==='object'&&v!==null):[]}private pem(value:string){return value.includes('BEGIN PUBLIC KEY')?value:`-----BEGIN PUBLIC KEY-----\n${value.match(/.{1,64}/gu)?.join('\n')??value}\n-----END PUBLIC KEY-----`}}
