apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amp-production
resources: [../../base]
patches:
  - target: { kind: Namespace, name: amp }
    patch: |-
      - op: replace
        path: /metadata/name
        value: amp-production
configMapGenerator:
  - name: amp-environment
    literals: [ENVIRONMENT=production]
