import { Brain, Download, Megaphone, Target, Users } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button, ChartCard, MetricCard, Select, Tabs } from '@/shared/ui';

const trend = [{ month: 'Feb', revenue: 118, leads: 920 }, { month: 'Mar', revenue: 132, leads: 1080 }, { month: 'Apr', revenue: 146, leads: 1240 }, { month: 'May', revenue: 158, leads: 1360 }, { month: 'Jun', revenue: 172, leads: 1480 }, { month: 'Jul', revenue: 194, leads: 1690 }];
const channels = [{ name: 'Organic', value: 36, color: '#6366f1' }, { name: 'Paid', value: 25, color: '#06b6d4' }, { name: 'Email', value: 22, color: '#8b5cf6' }, { name: 'Referral', value: 17, color: '#f59e0b' }];
const team = [{ name: 'Alex', revenue: 84 }, { name: 'Jordan', revenue: 72 }, { name: 'Sam', revenue: 68 }, { name: 'Morgan', revenue: 51 }];

export function AnalyticsPage() {
  const exportReport = () => { const url = URL.createObjectURL(new Blob([JSON.stringify({ trend, channels, team }, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'analytics-report.json'; anchor.click(); URL.revokeObjectURL(url); };
  const overview = <div className="grid gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard change={12.4} description="vs previous period" label="Attributed revenue" value="$194,200" /><MetricCard change={8.8} label="New leads" value="1,690" /><MetricCard change={3.2} label="Conversion rate" value="18.6%" /><MetricCard description="Blended return" label="Marketing ROI" value="4.8×" /></div><div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Revenue and lead trend" description="Six-month performance"><ResponsiveContainer height={260} width="100%"><AreaChart data={trend}><defs><linearGradient id="analytics-revenue" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#6366f1" stopOpacity={0.4} /><stop offset="100%" stopColor="#6366f1" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" /><YAxis /><Tooltip /><Area dataKey="revenue" fill="url(#analytics-revenue)" stroke="#6366f1" strokeWidth={2} type="monotone" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Channel attribution"><ResponsiveContainer height={260} width="100%"><PieChart><Pie data={channels} dataKey="value" innerRadius={55} nameKey="name" outerRadius={90}>{channels.map((item) => <Cell fill={item.color} key={item.name} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartCard></div></div>;
  const channelView = <div className="grid gap-4 md:grid-cols-2">{channels.map((channel) => <MetricCard description={`${channel.value}% of attributed conversions`} icon={<Megaphone />} key={channel.name} label={channel.name} value={`$${Math.round(194200 * channel.value / 100).toLocaleString()}`} />)}</div>;
  const teamView = <ChartCard title="Team sales analytics" description="Revenue in thousands"><ResponsiveContainer height={300} width="100%"><BarChart data={team}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="revenue" fill="#6366f1" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard>;
  return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-indigo-600">Business intelligence</p><h1 className="text-3xl font-bold">Analytics</h1><p className="text-sm text-slate-500">Understand attribution, channels, sales, AI, and team performance.</p></div><div className="flex gap-2"><Select aria-label="Date range" options={[{ label: 'Last 30 days', value: '30' }, { label: 'Last quarter', value: '90' }, { label: 'Year to date', value: 'ytd' }]} /><Button onClick={exportReport} variant="outline"><Download size={16} />Export</Button></div></header><Tabs defaultValue="reports" items={[{ label: 'Reports', value: 'reports', content: overview }, { label: 'Attribution', value: 'attribution', content: <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={<Target />} label="First-touch revenue" value="$72,400" /><MetricCard label="Last-touch revenue" value="$64,800" /><MetricCard label="Multi-touch revenue" value="$57,000" /></div> }, { label: 'Channels', value: 'channels', content: channelView }, { label: 'Sales', value: 'sales', content: teamView }, { label: 'AI analytics', value: 'ai', content: <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={<Brain />} label="AI conversations" value="4,842" /><MetricCard label="Resolution rate" value="81.4%" /><MetricCard label="Estimated hours saved" value="326" /></div> }, { label: 'Team', value: 'team', content: <div><div className="mb-4 grid gap-4 sm:grid-cols-3"><MetricCard icon={<Users />} label="Active teammates" value="18" /><MetricCard label="Tasks completed" value="1,284" /><MetricCard label="Average response" value="4m 18s" /></div>{teamView}</div> }]} /></div>;
}

export default AnalyticsPage;
