export const DOMAIN_NAMES = [
  'identity-access',
  'workspace-management',
  'crm',
  'sales',
  'tasks-scheduling',
  'messaging',
  'marketing-campaigns',
  'workflow-automation',
  'ai',
  'knowledge-management',
  'billing',
  'compliance',
  'integrations',
  'administration',
] as const;
export type DomainName = (typeof DOMAIN_NAMES)[number];

export interface DomainDefinition {
  readonly modules: readonly string[];
  readonly aggregateRoots: readonly string[];
  readonly entities: readonly string[];
  readonly valueObjects: readonly string[];
  readonly domainServices: readonly string[];
  readonly domainEvents: readonly string[];
  readonly integrationEvents: readonly string[];
  readonly commands: readonly string[];
  readonly queries: readonly string[];
  readonly repositories: readonly string[];
  readonly policies: readonly string[];
  readonly applicationServices: readonly string[];
  readonly infrastructureAdapters: readonly string[];
}

export const DOMAIN_MAP: Record<DomainName, DomainDefinition> = {
  'identity-access': {
    modules: ['auth', 'users', 'memberships', 'roles', 'permissions'],
    aggregateRoots: ['User', 'AuthSession', 'Role'],
    entities: ['RefreshToken', 'Membership'],
    valueObjects: ['EmailAddress', 'PasswordHash', 'PermissionKey'],
    domainServices: ['AuthenticationPolicy', 'PermissionPolicy'],
    domainEvents: ['UserRegistered', 'PasswordChanged', 'RolePermissionsChanged'],
    integrationEvents: ['IdentityAccessChanged'],
    commands: ['RegisterUser', 'AuthenticateUser', 'RevokeSession', 'AssignRole'],
    queries: ['GetCurrentUser', 'ListSessions', 'ResolvePermissions'],
    repositories: ['UserRepository', 'AuthSessionRepository', 'RoleRepository'],
    policies: ['PasswordPolicy', 'AccountLockoutPolicy', 'AuthorizationPolicy'],
    applicationServices: ['AuthService', 'PolicyService'],
    infrastructureAdapters: ['Argon2PasswordHasher', 'JwtTokenIssuer', 'MongoIdentityRepositories'],
  },
  'workspace-management': {
    modules: ['workspaces', 'workspace-settings', 'memberships'],
    aggregateRoots: ['Workspace'],
    entities: ['Membership', 'WorkspaceSettings'],
    valueObjects: ['WorkspaceSlug', 'Timezone', 'Locale', 'Currency'],
    domainServices: ['WorkspaceMembershipService'],
    domainEvents: ['WorkspaceCreated', 'MemberJoined', 'MemberSuspended'],
    integrationEvents: ['WorkspaceAccessChanged'],
    commands: ['CreateWorkspace', 'InviteMember', 'SuspendMember', 'UpdateWorkspaceSettings'],
    queries: ['GetWorkspace', 'ListMemberships'],
    repositories: ['WorkspaceRepository', 'MembershipRepository'],
    policies: ['WorkspaceAccessPolicy', 'WorkspaceLimitPolicy'],
    applicationServices: ['WorkspacesService', 'MembershipsService'],
    infrastructureAdapters: ['MongoWorkspaceRepositories'],
  },
  crm: {
    modules: ['contacts', 'companies', 'leads'],
    aggregateRoots: ['Contact', 'Company', 'Lead'],
    entities: ['ContactChannel', 'CompanyAssociation'],
    valueObjects: ['NormalizedEmail', 'NormalizedPhone', 'CustomField'],
    domainServices: ['ContactDeduplicationService'],
    domainEvents: ['ContactMerged', 'LeadConverted'],
    integrationEvents: ['ContactChanged', 'LeadChanged'],
    commands: ['CreateContact', 'MergeContacts', 'ConvertLead'],
    queries: ['SearchContacts', 'GetLead'],
    repositories: ['ContactRepository', 'CompanyRepository', 'LeadRepository'],
    policies: ['ContactMergePolicy', 'ConsentCommunicationPolicy'],
    applicationServices: ['ContactsService', 'CompaniesService', 'LeadsService'],
    infrastructureAdapters: ['MongoCrmRepositories', 'CrmImportExportQueue'],
  },
  sales: {
    modules: ['deals', 'pipelines'],
    aggregateRoots: ['Deal', 'Pipeline'],
    entities: ['PipelineStage'],
    valueObjects: ['Money', 'Probability', 'StageOrder'],
    domainServices: ['DealTransitionService'],
    domainEvents: ['DealStageChanged', 'DealWon', 'DealLost'],
    integrationEvents: ['SalesOutcomeChanged'],
    commands: ['MoveDeal', 'CloseDeal', 'ReorderStages'],
    queries: ['GetPipelineBoard', 'SearchDeals'],
    repositories: ['DealRepository', 'PipelineRepository'],
    policies: ['DealTransitionPolicy'],
    applicationServices: ['DealsService', 'PipelinesService'],
    infrastructureAdapters: ['MongoSalesRepositories'],
  },
  'tasks-scheduling': {
    modules: ['tasks', 'calendar', 'appointments', 'availability', 'booking-links', 'services'],
    aggregateRoots: ['Task', 'Appointment', 'BookingLink'],
    entities: ['ChecklistItem', 'AvailabilityRule', 'ServiceOffering'],
    valueObjects: ['TimeRange', 'Recurrence', 'Timezone'],
    domainServices: ['SchedulingConflictService'],
    domainEvents: ['AppointmentBooked', 'AppointmentRescheduled', 'TaskCompleted'],
    integrationEvents: ['ScheduleChanged'],
    commands: ['BookAppointment', 'RescheduleAppointment', 'CompleteTask'],
    queries: ['FindAvailability', 'ListTasks'],
    repositories: ['TaskRepository', 'AppointmentRepository', 'AvailabilityRepository'],
    policies: ['BookingPolicy', 'CancellationPolicy'],
    applicationServices: ['TasksService', 'AppointmentsService'],
    infrastructureAdapters: ['MongoSchedulingRepositories', 'ReminderQueue'],
  },
  messaging: {
    modules: ['inbox', 'notifications'],
    aggregateRoots: ['Conversation', 'OutboundMessage'],
    entities: ['Message', 'Participant', 'Assignment'],
    valueObjects: ['ChannelAddress', 'MessageBody', 'DeliveryState'],
    domainServices: ['ConversationRoutingService'],
    domainEvents: ['MessageReceived', 'MessageQueued', 'ConversationAssigned'],
    integrationEvents: ['InboundMessageReceived', 'MessageDeliveryChanged'],
    commands: ['SendMessage', 'AssignConversation', 'MarkConversationRead'],
    queries: ['ListConversations', 'GetConversationMessages'],
    repositories: ['ConversationRepository', 'MessageRepository'],
    policies: ['MessageDeliveryPolicy', 'InboxAccessPolicy'],
    applicationServices: ['InboxService'],
    infrastructureAdapters: ['ChannelProviderAdapters', 'InboxDeliveryQueue', 'SocketIoGateway'],
  },
  'marketing-campaigns': {
    modules: ['campaigns'],
    aggregateRoots: ['Campaign', 'CampaignRun'],
    entities: ['AudienceSnapshot', 'Delivery', 'Variant'],
    valueObjects: ['QuietHours', 'Personalization', 'AudienceRule'],
    domainServices: ['CampaignEligibilityService'],
    domainEvents: ['CampaignScheduled', 'CampaignPaused', 'DeliveryAttempted'],
    integrationEvents: ['CampaignDeliveryRequested', 'CampaignCompleted'],
    commands: ['ScheduleCampaign', 'PauseCampaign', 'CancelCampaign'],
    queries: ['GetCampaignAnalytics', 'PreviewAudience'],
    repositories: ['CampaignRepository', 'DeliveryRepository'],
    policies: ['ConsentPolicy', 'SuppressionPolicy', 'QuietHoursPolicy'],
    applicationServices: ['CampaignService'],
    infrastructureAdapters: ['CampaignDeliveryQueue', 'ProviderAdapters'],
  },
  'workflow-automation': {
    modules: ['workflows'],
    aggregateRoots: ['WorkflowDefinition', 'WorkflowRun'],
    entities: ['WorkflowVersion', 'StepRun', 'WaitState'],
    valueObjects: ['WorkflowGraph', 'RetryPolicy', 'NodeConfiguration'],
    domainServices: ['WorkflowGraphValidator', 'WorkflowExecutionEngine'],
    domainEvents: ['WorkflowPublished', 'StepCompleted', 'WorkflowFailed'],
    integrationEvents: ['WorkflowExecutionRequested', 'WorkflowRunCompleted'],
    commands: ['PublishWorkflow', 'StartWorkflow', 'CancelWorkflow', 'ResumeWorkflow'],
    queries: ['GetWorkflowHistory', 'GetWorkflowRun'],
    repositories: ['WorkflowRepository', 'WorkflowRunRepository'],
    policies: ['WorkflowConcurrencyPolicy'],
    applicationServices: ['WorkflowService'],
    infrastructureAdapters: ['BullMqWorkflowExecutor', 'MongoWorkflowRepositories'],
  },
  ai: {
    modules: ['agents'],
    aggregateRoots: ['AgentConfiguration'],
    entities: ['AiRun', 'ToolGrant'],
    valueObjects: ['ModelReference', 'TokenBudget', 'PromptTemplate'],
    domainServices: ['AiToolAuthorizationService'],
    domainEvents: ['AiRunCompleted', 'AiRunFailed'],
    integrationEvents: ['AiTaskRequested', 'AiUsageRecorded'],
    commands: ['RunAgent', 'CancelAiRun'],
    queries: ['GetAiRun', 'ListAvailableModels'],
    repositories: ['AgentRepository', 'AiRunRepository'],
    policies: ['AiBudgetPolicy', 'AiToolPolicy'],
    applicationServices: ['AgentApplicationService'],
    infrastructureAdapters: ['ModelProviderAdapters', 'AiQueue'],
  },
  'knowledge-management': {
    modules: ['knowledge-base', 'files'],
    aggregateRoots: ['KnowledgeBase', 'Document'],
    entities: ['DocumentChunk', 'FileAsset'],
    valueObjects: ['Checksum', 'EmbeddingVector', 'StorageKey'],
    domainServices: ['DocumentIngestionService'],
    domainEvents: ['DocumentIngested', 'DocumentRemoved'],
    integrationEvents: ['EmbeddingRequested', 'KnowledgeIndexChanged'],
    commands: ['UploadDocument', 'IndexDocument', 'RemoveDocument'],
    queries: ['SearchKnowledge', 'GetDocument'],
    repositories: ['KnowledgeRepository', 'FileRepository'],
    policies: ['FileAccessPolicy', 'RetentionPolicy'],
    applicationServices: ['FilesService', 'KnowledgeApplicationService'],
    infrastructureAdapters: [
      'ObjectStorageAdapter',
      'VectorSearchAdapter',
      'DocumentProcessingQueue',
    ],
  },
  billing: {
    modules: ['billing'],
    aggregateRoots: ['Subscription'],
    entities: ['BillingCustomer', 'Invoice', 'PaymentMethod', 'UsageSnapshot'],
    valueObjects: ['PlanCode', 'BillingInterval', 'UsageQuantity', 'Money'],
    domainServices: ['SubscriptionStateMachine', 'EntitlementService'],
    domainEvents: ['SubscriptionChanged', 'UsageLimitExceeded'],
    integrationEvents: ['EntitlementsChanged', 'BillingPaymentFailed'],
    commands: ['StartSubscription', 'ChangePlan', 'CancelSubscription', 'RecordUsage'],
    queries: ['GetSubscription', 'GetEntitlements', 'GetUsage'],
    repositories: ['BillingRepository'],
    policies: ['EntitlementPolicy', 'UsageLimitPolicy'],
    applicationServices: ['BillingService'],
    infrastructureAdapters: [
      'StripeBillingProvider',
      'FakeBillingProvider',
      'MongoBillingRepository',
    ],
  },
  compliance: {
    modules: ['consent', 'compliance', 'audit'],
    aggregateRoots: ['ConsentRecord', 'ComplianceCase'],
    entities: ['AuditEntry', 'SuppressionEntry'],
    valueObjects: ['LegalBasis', 'RetentionPeriod', 'ConsentChannel'],
    domainServices: ['RetentionService'],
    domainEvents: ['ConsentChanged', 'ErasureRequested'],
    integrationEvents: ['CommunicationPermissionChanged'],
    commands: ['RecordConsent', 'RequestErasure', 'ExportSubjectData'],
    queries: ['GetConsentHistory', 'GetAuditTrail'],
    repositories: ['ConsentRepository', 'AuditRepository'],
    policies: ['DataRetentionPolicy', 'ErasurePolicy'],
    applicationServices: ['ComplianceApplicationService'],
    infrastructureAdapters: ['ComplianceExportQueue', 'MongoComplianceRepositories'],
  },
  integrations: {
    modules: ['integrations'],
    aggregateRoots: ['IntegrationConnection'],
    entities: ['Credential', 'WebhookEvent', 'SyncJob'],
    valueObjects: ['ProviderName', 'EncryptedCredential', 'WebhookSignature'],
    domainServices: ['WebhookVerificationService'],
    domainEvents: ['ConnectionEstablished', 'ConnectionRevoked'],
    integrationEvents: ['ProviderWebhookAccepted', 'SyncCompleted'],
    commands: ['ConnectProvider', 'DisconnectProvider', 'ProcessWebhook', 'StartSync'],
    queries: ['GetConnectionHealth', 'ListConnections'],
    repositories: ['IntegrationRepository'],
    policies: ['OAuthStatePolicy', 'WebhookReplayPolicy'],
    applicationServices: ['IntegrationService'],
    infrastructureAdapters: ['OAuthProviderAdapters', 'CredentialVault', 'WebhookProcessingQueue'],
  },
  administration: {
    modules: ['admin'],
    aggregateRoots: ['PlatformConfiguration'],
    entities: ['AdministrativeAction'],
    valueObjects: ['AdminPermission', 'FeatureFlag'],
    domainServices: ['PlatformAdministrationService'],
    domainEvents: ['PlatformSettingChanged'],
    integrationEvents: ['PlatformConfigurationChanged'],
    commands: ['UpdatePlatformSetting', 'PerformPlatformOperation'],
    queries: ['GetPlatformStatus', 'GetAdministrativeAudit'],
    repositories: ['PlatformConfigurationRepository'],
    policies: ['PlatformAdminPolicy'],
    applicationServices: ['AdminApplicationService'],
    infrastructureAdapters: ['MongoAdminRepository'],
  },
};
