import { Check, CreditCard, Download, Receipt, Tag, Zap } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Input, MetricCard, Table, Tabs, type TableColumn } from '@/shared/ui';

interface Invoice { id: string; date: string; amount: string; status: string }
const invoices: Invoice[] = [{ id: 'INV-2048', date: 'Jul 1, 2026', amount: '$249.00', status: 'Paid' }, { id: 'INV-1982', date: 'Jun 1, 2026', amount: '$249.00', status: 'Paid' }, { id: 'INV-1914', date: 'May 1, 2026', amount: '$249.00', status: 'Paid' }];
const plans = [{ name: 'Starter', price: 49, features: ['3 team members', '5,000 contacts', 'Basic automation'] }, { name: 'Growth', price: 249, popular: true, features: ['15 team members', '50,000 contacts', 'AI agents', 'Advanced automation'] }, { name: 'Scale', price: 699, features: ['Unlimited team', '250,000 contacts', 'Priority support', 'Custom limits'] }];

export function BillingPage() {
  const [coupon, setCoupon] = useState(''); const columns: TableColumn<Invoice>[] = [{ key: 'id', header: 'Invoice', render: (row) => <strong>{row.id}</strong> }, { key: 'date', header: 'Date', render: (row) => row.date }, { key: 'amount', header: 'Amount', align: 'right', render: (row) => row.amount }, { key: 'status', header: 'Status', render: (row) => <Badge tone="success">{row.status}</Badge> }, { key: 'download', header: '', render: () => <Button aria-label="Download invoice" size="sm" variant="ghost"><Download size={15} /></Button> }];
  const overview = <div className="grid gap-6"><section className="rounded-xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-white p-6 dark:border-indigo-900 dark:from-indigo-950 dark:to-slate-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><Badge tone="primary">Current plan</Badge><h2 className="mt-3 text-2xl font-bold">Growth</h2><p className="text-sm text-slate-500">$249 monthly · renews August 1, 2026</p></div><Button variant="outline">Manage subscription</Button></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><MetricCard label="Contacts" value="32,840 / 50k" /><MetricCard label="AI credits" value="68k / 100k" /><MetricCard label="Team seats" value="11 / 15" /></div></section><div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={<Zap />} label="AI usage this month" value="68,420" /><MetricCard icon={<CreditCard />} label="Next payment" value="$249.00" /><MetricCard icon={<Receipt />} label="Billing cycle" value="Monthly" /></div></div>;
  const planView = <div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article className={`rounded-xl border bg-white p-6 dark:bg-slate-900 ${plan.popular ? 'border-indigo-500 ring-1 ring-indigo-500' : 'border-slate-200 dark:border-slate-700'}`} key={plan.name}>{plan.popular ? <Badge tone="primary">Most popular</Badge> : null}<h2 className="mt-3 text-xl font-bold">{plan.name}</h2><p className="mt-2 text-3xl font-bold">${plan.price}<span className="text-sm font-normal text-slate-500">/month</span></p><ul className="mt-5 space-y-3 text-sm">{plan.features.map((feature) => <li className="flex gap-2" key={feature}><Check className="text-emerald-500" size={16} />{feature}</li>)}</ul><Button className="mt-6 w-full" variant={plan.name === 'Growth' ? 'secondary' : 'outline'}>{plan.name === 'Growth' ? 'Current plan' : 'Choose plan'}</Button></article>)}</div>;
  return <div className="grid gap-6"><header><p className="text-sm font-medium text-indigo-600">Workspace billing</p><h1 className="text-3xl font-bold">Billing</h1><p className="text-sm text-slate-500">Manage plans, payments, invoices, and usage.</p></header><Tabs defaultValue="overview" items={[{ label: 'Subscription', value: 'overview', content: overview }, { label: 'Plans', value: 'plans', content: planView }, { label: 'Invoices', value: 'invoices', content: <Table columns={columns} getRowKey={(row) => row.id} rows={invoices} /> }, { label: 'Payment methods', value: 'payment', content: <section className="max-w-xl rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center gap-3"><CreditCard /><div><strong>Visa ending in 4242</strong><p className="text-xs text-slate-500">Expires 08/29 · Default</p></div><Button className="ml-auto" variant="outline">Update</Button></div></section> }, { label: 'Coupons', value: 'coupons', content: <section className="max-w-xl rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h2 className="flex items-center gap-2 font-semibold"><Tag size={17} />Apply coupon</h2><div className="mt-4 flex gap-2"><Input aria-label="Coupon code" onChange={(event) => setCoupon(event.target.value)} placeholder="ENTER-CODE" value={coupon} /><Button disabled={!coupon.trim()}>Apply</Button></div></section> }]} /></div>;
}

export default BillingPage;
