import { Copy, Trash2 } from 'lucide-react';
import { Button, EmptyState, Input, Select, Textarea } from '@/shared/ui';
import type { WorkflowNode } from '../types/workflow.types';

export function NodeInspector({ node, onDelete, onDuplicate, onUpdate }: { node?: WorkflowNode; onDelete: () => void; onDuplicate: () => void; onUpdate: (data: WorkflowNode['data']) => void }) {
  if (!node) return <aside className="min-h-0 overflow-y-auto border-l border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><EmptyState description="Select a node to configure its behavior." title="No node selected" /></aside>;
  const updateConfig = (key: string, value: string) => onUpdate({ ...node.data, config: { ...node.data.config, [key]: value } });
  return <aside className="min-h-0 overflow-y-auto border-l border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><div><p className="text-xs font-bold uppercase text-indigo-600 dark:text-indigo-400">{node.data.category}</p><h2 className="font-semibold">Node inspector</h2></div><Button aria-label="Duplicate node" className="ml-auto" onClick={onDuplicate} size="sm" variant="ghost"><Copy size={16} /></Button><Button aria-label="Delete node" onClick={onDelete} size="sm" variant="ghost"><Trash2 className="text-red-500" size={16} /></Button></div><div className="mt-5 grid gap-4"><Input label="Display name" onChange={(event) => onUpdate({ ...node.data, label: event.target.value })} value={node.data.label} /><Textarea label="Description" onChange={(event) => onUpdate({ ...node.data, description: event.target.value })} rows={3} value={node.data.description} />{node.data.category === 'trigger' ? <Select label="Enrollment frequency" onChange={(event) => updateConfig('frequency', event.target.value)} options={[{ label: 'Once per contact', value: 'once' }, { label: 'Every time', value: 'always' }]} value={node.data.config.frequency ?? 'once'} /> : null}{node.data.category === 'action' ? <Textarea label="Action content" onChange={(event) => updateConfig('content', event.target.value)} placeholder="Configure the mock action…" value={node.data.config.content ?? ''} /> : null}{node.data.category === 'logic' ? <Input label="Rule or duration" onChange={(event) => updateConfig('rule', event.target.value)} placeholder="e.g. Lead score > 70" value={node.data.config.rule ?? ''} /> : null}{node.data.category === 'ai' ? <Textarea label="AI instructions" onChange={(event) => updateConfig('prompt', event.target.value)} placeholder="Describe the desired mock AI behavior…" value={node.data.config.prompt ?? ''} /> : null}<p className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-900">This configuration is stored in the workflow JSON. No automation or AI service is executed.</p></div></aside>;
}
