import{Prop,Schema,SchemaFactory}from'@nestjs/mongoose';import{HydratedDocument,Schema as MongooseSchema,Types}from'mongoose';
@Schema({collection:'workflow_definitions',timestamps:true,versionKey:false})export class WorkflowDefinition{_id!:Types.ObjectId;createdAt!:Date;updatedAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:String,required:true})name!:string;@Prop({type:String,default:''})description!:string;@Prop({type:String,enum:['active','inactive','archived'],default:'inactive'})status!:string;@Prop({type:Number,default:0})latestVersion!:number;@Prop({type:Number,default:null})publishedVersion!:number|null;@Prop({type:MongooseSchema.Types.ObjectId,required:true})createdBy!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})updatedBy!:Types.ObjectId}
export type WorkflowDefinitionDocument=HydratedDocument<WorkflowDefinition>;export const WorkflowDefinitionSchema=SchemaFactory.createForClass(WorkflowDefinition);WorkflowDefinitionSchema.index({workspaceId:1,status:1,updatedAt:-1});
@Schema({collection:'workflow_versions',timestamps:true,versionKey:false})export class WorkflowVersion{_id!:Types.ObjectId;createdAt!:Date;updatedAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowDefinitionId!:Types.ObjectId;@Prop({type:Number,required:true})version!:number;@Prop({type:String,enum:['draft','published','superseded'],default:'draft'})status!:string;@Prop({type:MongooseSchema.Types.Mixed,required:true})graph!:Record<string,unknown>;@Prop({type:Date,default:null})publishedAt!:Date|null;@Prop({type:MongooseSchema.Types.ObjectId,default:null})publishedBy!:Types.ObjectId|null;@Prop({type:String,default:null})checksum!:string|null}
export type WorkflowVersionDocument=HydratedDocument<WorkflowVersion>;export const WorkflowVersionSchema=SchemaFactory.createForClass(WorkflowVersion);WorkflowVersionSchema.index({workspaceId:1,workflowDefinitionId:1,version:1},{unique:true});
@Schema({collection:'workflow_runs',timestamps:true,versionKey:false})export class WorkflowRun{_id!:Types.ObjectId;createdAt!:Date;updatedAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowDefinitionId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowVersionId!:Types.ObjectId;@Prop({type:String,enum:['queued','running','waiting','paused','completed','failed','dead_letter','cancelled'],default:'queued'})status!:string;@Prop({type:String,required:true})correlationId!:string;@Prop({type:String,required:true})idempotencyKey!:string;@Prop({type:String,required:true})triggerType!:string;@Prop({type:MongooseSchema.Types.Mixed,default:{}})input!:Record<string,unknown>;@Prop({type:MongooseSchema.Types.Mixed,default:{}})variables!:Record<string,unknown>;@Prop({type:Number,default:0})activeJobs!:number;@Prop({type:String,default:null})failureReason!:string|null;@Prop({type:Date,default:null})completedAt!:Date|null}
export type WorkflowRunDocument=HydratedDocument<WorkflowRun>;export const WorkflowRunSchema=SchemaFactory.createForClass(WorkflowRun);WorkflowRunSchema.index({workspaceId:1,idempotencyKey:1},{unique:true});WorkflowRunSchema.index({workspaceId:1,status:1,createdAt:-1});
@Schema({collection:'workflow_step_runs',timestamps:true,versionKey:false})export class WorkflowStepRun{_id!:Types.ObjectId;createdAt!:Date;updatedAt!:Date;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowRunId!:Types.ObjectId;@Prop({type:String,required:true})nodeId!:string;@Prop({type:String,required:true})nodeType!:string;@Prop({type:String,enum:['running','completed','waiting','failed','cancelled'],required:true})status!:string;@Prop({type:Number,default:1})attempt!:number;@Prop({type:MongooseSchema.Types.Mixed,default:{}})input!:Record<string,unknown>;@Prop({type:MongooseSchema.Types.Mixed,default:{}})output!:Record<string,unknown>;@Prop({type:String,default:null})errorCode!:string|null;@Prop({type:String,default:null})errorMessage!:string|null;@Prop({type:Date,default:null})completedAt!:Date|null}
export type WorkflowStepRunDocument=HydratedDocument<WorkflowStepRun>;export const WorkflowStepRunSchema=SchemaFactory.createForClass(WorkflowStepRun);WorkflowStepRunSchema.index({workspaceId:1,workflowRunId:1,createdAt:1});
@Schema({collection:'workflow_wait_states',timestamps:true,versionKey:false})export class WorkflowWaitState{_id!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowRunId!:Types.ObjectId;@Prop({type:String,required:true})nodeId!:string;@Prop({type:Date,required:true})resumeAt!:Date;@Prop({type:String,enum:['waiting','resumed','cancelled'],default:'waiting'})status!:string}
export const WorkflowWaitStateSchema=SchemaFactory.createForClass(WorkflowWaitState);WorkflowWaitStateSchema.index({workspaceId:1,status:1,resumeAt:1});
@Schema({collection:'workflow_deduplication_keys',timestamps:true,versionKey:false})export class WorkflowDeduplicationKey{@Prop({type:MongooseSchema.Types.ObjectId,required:true})workspaceId!:Types.ObjectId;@Prop({type:String,required:true})key!:string;@Prop({type:MongooseSchema.Types.ObjectId,required:true})workflowRunId!:Types.ObjectId;@Prop({type:Date,required:true})expiresAt!:Date}
export const WorkflowDeduplicationKeySchema=SchemaFactory.createForClass(WorkflowDeduplicationKey);WorkflowDeduplicationKeySchema.index({workspaceId:1,key:1},{unique:true});WorkflowDeduplicationKeySchema.index({expiresAt:1},{expireAfterSeconds:0});
