import{InjectQueue}from'@nestjs/bullmq';import{BadRequestException,Injectable,UnauthorizedException}from'@nestjs/common';import type{Queue}from'bullmq';import{createHash}from'node:crypto';import{Types}from'mongoose';import type{WorkspaceRequestContext}from'../../../common/types/workspace-context.js';import{CreateConnectionDto,OAuthCallbackDto,SyncDto}from'../dto/integration.dto.js';import{ProviderRegistry}from'../providers/provider.registry.js';import{IntegrationRepository}from'../repositories/integration.repository.js';import type{IntegrationConnection,IntegrationWebhookEvent}from'../schemas/integration.schemas.js';import type{ProviderConnectionContext}from'../types/provider-adapter.js';import{CredentialVaultService}from'./credential-vault.service.js';import{OAuthService}from'./oauth.service.js';
export const INTEGRATION_QUEUE='integration-jobs';
export type StoredIntegrationWebhookEvent=IntegrationWebhookEvent;
const mapConnection=(v:IntegrationConnection)=>({id:String(v._id),provider:v.provider,name:v.name,status:v.status,publicMetadata:v.publicMetadata,lastValidatedAt:v.lastValidatedAt,lastSyncAt:v.lastSyncAt,lastErrorCode:v.lastErrorCode,createdAt:v.createdAt,updatedAt:v.updatedAt});
@Injectable()export class IntegrationService{constructor(private readonly repository:IntegrationRepository,private readonly registry:ProviderRegistry,private readonly vault:CredentialVaultService,private readonly oauth:OAuthService,@InjectQueue(INTEGRATION_QUEUE)private readonly queue:Queue){}
 async create(c:WorkspaceRequestContext,d:CreateConnectionDto){return mapConnection(await this.repository.createConnection(c.workspaceId,c.userId,d.provider,d.name))}
 async beginOAuth(c:WorkspaceRequestContext,connectionId:string,redirectUri:string){const connection=await this.repository.connection(c.workspaceId,connectionId);return this.oauth.begin({workspaceId:c.workspaceId,userId:c.userId,provider:connection.provider as ProviderConnectionContext['provider'],connectionId,redirectUri})}
 async callback(d:OAuthCallbackDto){const state=await this.oauth.consume(d.state),adapter=this.registry.get(state.provider);const credentials=await adapter.connect({code:d.code,codeVerifier:state.codeVerifier,redirectUri:state.redirectUri});await this.repository.saveCredentials(state.workspaceId,state.connectionId,this.vault.seal(credentials),credentials.expiresAt?new Date(credentials.expiresAt):undefined);await this.repository.setConnection(state.workspaceId,state.connectionId,{$set:{status:'active',lastErrorCode:null}});return{connected:true,connectionId:state.connectionId}}
 async disconnect(c:WorkspaceRequestContext,id:string){const context=await this.context(c.workspaceId,id);await this.registry.get(context.provider).disconnect(context);await this.repository.setConnection(c.workspaceId,id,{$set:{status:'disabled'}});return{disconnected:true}}
 async validate(c:WorkspaceRequestContext,id:string){const context=await this.context(c.workspaceId,id),valid=await this.registry.get(context.provider).validateConnection(context);await this.repository.setConnection(c.workspaceId,id,{$set:{status:valid?'active':'error',lastValidatedAt:new Date(),lastErrorCode:valid?null:'validation_failed'}});return{valid}}
 async refresh(c:WorkspaceRequestContext,id:string){const context=await this.context(c.workspaceId,id),credentials=await this.registry.get(context.provider).refreshCredentials(context);await this.repository.saveCredentials(c.workspaceId,id,this.vault.seal(credentials),credentials.expiresAt?new Date(credentials.expiresAt):undefined);return{refreshed:true}}
 async sync(c:WorkspaceRequestContext,id:string,d:SyncDto){await this.repository.connection(c.workspaceId,id);const result=await this.repository.reserveSync(c.workspaceId,id,d.resource,d.idempotencyKey),syncJobId=this.documentId(result.job);if(!result.duplicate)await this.queue.add('integration.sync',{workspaceId:c.workspaceId,syncJobId,connectionId:id,resource:d.resource,cursor:d.cursor,limit:d.limit},{jobId:`sync-${syncJobId}`,attempts:5,backoff:{type:'exponential',delay:1000}});return{syncJobId,duplicate:result.duplicate}}
 async webhook(workspaceId:string,connectionId:string,rawBody:Buffer,headers:Record<string,string|undefined>){const connection=await this.repository.connection(workspaceId,connectionId),credential=await this.repository.credential(workspaceId,connectionId),credentials=this.vault.open(credential.encryptedPayload),secret=credentials.webhookSecret;if(!secret)throw new UnauthorizedException('Webhook secret is not configured');const adapter=this.registry.get(connection.provider as ProviderConnectionContext['provider']);if(!adapter.verifyWebhook(rawBody,headers,secret,300))throw new UnauthorizedException('Invalid webhook signature or timestamp');const envelope=await adapter.handleWebhook(rawBody,headers);if(!envelope.eventId)throw new BadRequestException('Provider event ID is required');const reserved=await this.repository.reserveWebhook({workspaceId,connectionId,provider:connection.provider,providerEventId:envelope.eventId,eventType:envelope.eventType,providerTimestamp:envelope.timestamp,payloadHash:createHash('sha256').update(rawBody).digest('hex'),payload:envelope.payload});if(!reserved.duplicate)await this.queue.add('integration.webhook',{workspaceId,eventId:String(reserved.event._id)},{jobId:`webhook-${String(reserved.event._id)}`,attempts:5,backoff:{type:'exponential',delay:1000}});return{accepted:true,duplicate:reserved.duplicate}}
 async health(c:WorkspaceRequestContext,id:string){const context=await this.context(c.workspaceId,id),result=await this.registry.get(context.provider).healthCheck(context);await this.repository.recordHealth({workspaceId:new Types.ObjectId(c.workspaceId),connectionId:new Types.ObjectId(id),...result});return result}
 async context(workspaceId:string,id:string):Promise<ProviderConnectionContext>{const connection=await this.repository.connection(workspaceId,id),credential=await this.repository.credential(workspaceId,id);return{workspaceId,connectionId:id,provider:connection.provider as ProviderConnectionContext['provider'],credentials:this.vault.open(credential.encryptedPayload)}}
 private documentId(value:object){return String((value as {_id:unknown})._id)}
}
