import { InjectQueue } from '@nestjs/bullmq';
import { BadRequestException, Injectable } from '@nestjs/common';
import type { Queue } from 'bullmq';
import { createHash } from 'node:crypto';
import type { WorkspaceRequestContext } from '../../../common/types/workspace-context.js';
import type { CreateMetaConversionDto } from '../dto/integration.dto.js';
import { MetaConversionsService,type PreparedMetaConversion } from '../providers/meta/meta-conversions.service.js';
import { IntegrationRepository } from '../repositories/integration.repository.js';
import { INTEGRATION_QUEUE,IntegrationService } from './integration.service.js';
const STANDARD_EVENTS=new Set(['Lead','Contact','Schedule','Purchase']);
export interface MetaConversionJob{workspaceId:string;connectionId:string;deliveryId:string;pixelId:string;event:PreparedMetaConversion;testEventCode?:string}
@Injectable()
export class MetaConversionDeliveryService{
 constructor(private readonly repository:IntegrationRepository,private readonly integrations:IntegrationService,private readonly conversions:MetaConversionsService,@InjectQueue(INTEGRATION_QUEUE)private readonly queue:Queue){}
 async enqueue(c:WorkspaceRequestContext,connectionId:string,d:CreateMetaConversionDto){if(!STANDARD_EVENTS.has(d.eventName)&&!d.allowCustomEvent)throw new BadRequestException('Custom Meta events require allowCustomEvent=true');const context=await this.integrations.context(c.workspaceId,connectionId);if(context.provider!=='facebook'&&context.provider!=='instagram')throw new BadRequestException('Conversions API requires a Meta connection');const pixelId=d.pixelId??context.credentials.selectedResourceIds?.pixels?.[0];if(!pixelId)throw new BadRequestException('Select a Meta Pixel before sending conversion events');const eventTime=new Date(d.eventTime);if(eventTime.getTime()<Date.now()-7*86_400_000||eventTime.getTime()>Date.now()+5*60_000)throw new BadRequestException('Meta conversion event_time must be within the last seven days and not in the future');const eventId=d.eventId??(d.sourceEventId?this.stableId(c.workspaceId,connectionId,d.eventName,d.sourceEventId):'');if(!eventId)throw new BadRequestException('eventId or sourceEventId is required for deterministic deduplication');const event=this.conversions.prepare({eventName:d.eventName,eventTime,eventId,actionSource:d.actionSource,...(d.eventSourceUrl?{eventSourceUrl:d.eventSourceUrl}:{}),customer:d.customer,customData:d.customData,...(d.testEventCode?{testEventCode:d.testEventCode}:{})}),payloadHash=createHash('sha256').update(JSON.stringify(event)).digest('hex'),reserved=await this.repository.reserveConversion({workspaceId:c.workspaceId,connectionId,eventId,eventName:d.eventName,pixelId,payloadHash}),deliveryId=String(reserved.delivery._id);if(!reserved.duplicate)await this.queue.add('meta.conversion',{workspaceId:c.workspaceId,connectionId,deliveryId,pixelId,event,...(d.testEventCode?{testEventCode:d.testEventCode}:{})}satisfies MetaConversionJob,{jobId:`meta-conversion-${deliveryId}`,attempts:5,backoff:{type:'exponential',delay:1_000},removeOnComplete:1_000,removeOnFail:false});return{deliveryId,eventId,duplicate:reserved.duplicate,status:reserved.delivery.status};}
 async process(data:MetaConversionJob,attempt:number){const delivery=await this.repository.claimConversion(data.workspaceId,data.deliveryId);if(!delivery)return{duplicate:true};try{const response=await this.conversions.send(await this.integrations.context(data.workspaceId,data.connectionId),data.pixelId,data.event,data.testEventCode);const summary={eventsReceived:Number(response.events_received??0),messageCount:response.messages?.length??0};await this.repository.updateConversion(data.workspaceId,data.deliveryId,{$set:{status:'delivered',deliveredAt:new Date(),responseStatus:200,responseSummary:summary,errorCode:null}});return summary;}catch(error:unknown){const dead=attempt>=5;await this.repository.updateConversion(data.workspaceId,data.deliveryId,{$set:{status:dead?'dead_letter':'failed',errorCode:this.errorCode(error),responseSummary:null}});throw error;}}
 async status(c:WorkspaceRequestContext,connectionId:string,deliveryId:string){const value=await this.repository.conversion(c.workspaceId,connectionId,deliveryId);return{id:String(value._id),eventId:value.eventId,eventName:value.eventName,pixelId:value.pixelId,status:value.status,attemptCount:value.attemptCount,responseStatus:value.responseStatus,responseSummary:value.responseSummary,errorCode:value.errorCode,deliveredAt:value.deliveredAt};}
 private stableId(workspaceId:string,connectionId:string,eventName:string,sourceEventId:string){return createHash('sha256').update(`${workspaceId}:${connectionId}:${eventName}:${sourceEventId}`).digest('hex');}
 private errorCode(error:unknown){return error instanceof Error?error.name.slice(0,100):'META_CONVERSION_ERROR';}
}
