import { MailPlus, ShieldCheck, Users } from 'lucide-react';
import { useState } from 'react';
import { Avatar, Badge, Button, Checkbox, Input, Modal, Select, Table, Tabs, type TableColumn } from '@/shared/ui';

interface Member { id: string; name: string; email: string; role: string; status: 'active' | 'invited'; lastActive: string }
const seed: Member[] = [{ id: 'u1', name: 'Alex Morgan', email: 'alex@acme.io', role: 'Admin', status: 'active', lastActive: '2 min ago' }, { id: 'u2', name: 'Jordan Lee', email: 'jordan@acme.io', role: 'Sales manager', status: 'active', lastActive: '18 min ago' }, { id: 'u3', name: 'Sam Rivera', email: 'sam@acme.io', role: 'Member', status: 'active', lastActive: 'Yesterday' }, { id: 'u4', name: 'Morgan Chen', email: 'morgan@acme.io', role: 'Member', status: 'invited', lastActive: 'Invitation pending' }];

export function TeamPage() {
  const [members, setMembers] = useState(seed); const [open, setOpen] = useState(false); const [email, setEmail] = useState(''); const [role, setRole] = useState('Member');
  const columns: TableColumn<Member>[] = [{ key: 'member', header: 'Member', render: (row) => <div className="flex items-center gap-3"><Avatar alt={row.name} size="sm" /><div><strong>{row.name}</strong><p className="text-xs text-slate-500">{row.email}</p></div></div> }, { key: 'role', header: 'Role', render: (row) => <Select aria-label={`Role for ${row.name}`} onChange={(event) => setMembers((current) => current.map((member) => member.id === row.id ? { ...member, role: event.target.value } : member))} options={['Admin', 'Sales manager', 'Member', 'Viewer'].map((value) => ({ label: value, value }))} value={row.role} /> }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'active' ? 'success' : 'warning'}>{row.status}</Badge> }, { key: 'active', header: 'Last active', render: (row) => row.lastActive }];
  const roles = <div className="grid gap-4 md:grid-cols-2">{['Admin', 'Sales manager', 'Member', 'Viewer'].map((item, index) => <section className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900" key={item}><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck size={17} />{item}</h2><p className="mt-2 text-sm text-slate-500">{index === 0 ? 'Full workspace and billing access.' : index === 1 ? 'Manage sales records, team assignments, and reports.' : index === 2 ? 'Create and update assigned workspace records.' : 'Read-only access to selected modules.'}</p><div className="mt-4 grid gap-2"><Checkbox checked={index < 3} label="Manage contacts" readOnly /><Checkbox checked={index < 2} label="Manage team" readOnly /><Checkbox checked={index === 0} label="Manage billing" readOnly /></div></section>)}</div>;
  return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-indigo-600">Workspace access</p><h1 className="text-3xl font-bold">Team</h1><p className="text-sm text-slate-500">Manage members, invitations, roles, and permissions.</p></div><Button onClick={() => setOpen(true)}><MailPlus size={16} />Invite member</Button></header><Tabs defaultValue="members" items={[{ label: `Members (${members.length})`, value: 'members', content: <Table columns={columns} getRowKey={(row) => row.id} rows={members} /> }, { label: 'Roles & permissions', value: 'roles', content: roles }]} /><Modal onClose={() => setOpen(false)} open={open} title="Invite teammate"><form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); if (!email.trim()) return; setMembers((current) => [...current, { id: crypto.randomUUID(), name: email.split('@')[0] ?? 'New member', email, role, status: 'invited', lastActive: 'Invitation pending' }]); setEmail(''); setOpen(false); }}><Input label="Email address" onChange={(event) => setEmail(event.target.value)} type="email" value={email} /><Select label="Role" onChange={(event) => setRole(event.target.value)} options={['Admin', 'Sales manager', 'Member', 'Viewer'].map((value) => ({ label: value, value }))} value={role} /><Button disabled={!email.trim()} type="submit"><Users size={16} />Send invitation</Button></form></Modal></div>;
}

export default TeamPage;
