import{Injectable,NotFoundException}from'@nestjs/common';import{InjectModel}from'@nestjs/mongoose';import type{Model}from'mongoose';import{Types}from'mongoose';import{IntegrationConnection,type IntegrationConnectionDocument,IntegrationConversionDelivery,IntegrationCredential,IntegrationProviderHealth,IntegrationSyncJob,IntegrationWebhookDelivery,IntegrationWebhookEvent}from'../schemas/integration.schemas.js';import type{Provider}from'../types/provider-adapter.js';
@Injectable()export class IntegrationRepository{constructor(@InjectModel(IntegrationConnection.name)private readonly connections:Model<IntegrationConnectionDocument>,@InjectModel(IntegrationCredential.name)private readonly credentials:Model<IntegrationCredential>,@InjectModel(IntegrationWebhookEvent.name)private readonly events:Model<IntegrationWebhookEvent>,@InjectModel(IntegrationWebhookDelivery.name)private readonly deliveries:Model<IntegrationWebhookDelivery>,@InjectModel(IntegrationSyncJob.name)private readonly syncJobs:Model<IntegrationSyncJob>,@InjectModel(IntegrationProviderHealth.name)private readonly health:Model<IntegrationProviderHealth>,@InjectModel(IntegrationConversionDelivery.name)private readonly conversions:Model<IntegrationConversionDelivery>){}
 async createConnection(workspaceId:string,userId:string,provider:Provider,name:string){const value=new this.connections({workspaceId:new Types.ObjectId(workspaceId),createdBy:new Types.ObjectId(userId),provider,name});await value.save();return value.toObject()}
 async connection(workspaceId:string,id:string){const value=await this.connections.findOne({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId)}).lean<IntegrationConnection>().exec();if(!value)throw new NotFoundException('Integration connection not found');return value}
 listConnections(workspaceId:string){return this.connections.find({workspaceId:new Types.ObjectId(workspaceId)}).sort({createdAt:-1}).lean<IntegrationConnection[]>().exec()}
 setConnection(workspaceId:string,id:string,update:object){return this.connections.findOneAndUpdate({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId)},update,{new:true}).lean<IntegrationConnection>().exec()}
 async saveCredentials(workspaceId:string,connectionId:string,encryptedPayload:string,expiresAt?:Date){await this.credentials.updateOne({workspaceId:new Types.ObjectId(workspaceId),connectionId:new Types.ObjectId(connectionId)},{$set:{encryptedPayload,expiresAt:expiresAt??null,keyVersion:1}},{upsert:true})}
 async credential(workspaceId:string,connectionId:string){const value=await this.credentials.findOne({workspaceId:new Types.ObjectId(workspaceId),connectionId:new Types.ObjectId(connectionId)}).select('+encryptedPayload').lean<IntegrationCredential>().exec();if(!value)throw new NotFoundException('Integration credentials not found');return value}
 async reserveWebhook(input:{workspaceId:string;connectionId:string;provider:string;providerEventId:string;eventType:string;providerTimestamp:Date;payloadHash:string;payload:Record<string,unknown>}){const key={workspaceId:new Types.ObjectId(input.workspaceId),connectionId:new Types.ObjectId(input.connectionId),providerEventId:input.providerEventId},existing=await this.events.findOne(key).lean<IntegrationWebhookEvent>().exec();if(existing)return{event:existing,duplicate:true};const event=new this.events({...input,...key});try{await event.save();return{event:event.toObject(),duplicate:false}}catch(error:unknown){if(typeof error!=='object'||error===null||!('code'in error)||error.code!==11000)throw error;const raced=await this.events.findOne(key).lean<IntegrationWebhookEvent>().exec();if(!raced)throw error;return{event:raced,duplicate:true}}}
 claimWebhook(workspaceId:string,id:string){return this.events.findOneAndUpdate({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId),status:{$in:['queued','failed']}},{$set:{status:'processing'},$inc:{attemptCount:1}},{new:true}).lean<IntegrationWebhookEvent>().exec()}
 updateWebhook(workspaceId:string,id:string,update:object){return this.events.updateOne({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId)},update)}
 logDelivery(input:object){return new this.deliveries(input).save()}
 async reserveSync(workspaceId:string,connectionId:string,resource:string,key:string){const existing=await this.syncJobs.findOne({workspaceId:new Types.ObjectId(workspaceId),idempotencyKey:key}).lean<IntegrationSyncJob>().exec();if(existing)return{job:existing,duplicate:true};const job=new this.syncJobs({workspaceId:new Types.ObjectId(workspaceId),connectionId:new Types.ObjectId(connectionId),resource,idempotencyKey:key});await job.save();return{job:job.toObject(),duplicate:false}}
 syncJob(workspaceId:string,id:string){return this.syncJobs.findOneAndUpdate({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId),status:{$in:['queued','failed']}},{$set:{status:'running'},$inc:{attemptCount:1}},{new:true}).lean<IntegrationSyncJob>().exec()}
 updateSync(workspaceId:string,id:string,update:object){return this.syncJobs.updateOne({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId)},update)}
 recordHealth(input:object){return new this.health(input).save()}
 async reserveConversion(input:{workspaceId:string;connectionId:string;eventId:string;eventName:string;pixelId:string;payloadHash:string}){const key={workspaceId:new Types.ObjectId(input.workspaceId),connectionId:new Types.ObjectId(input.connectionId),eventId:input.eventId},existing=await this.conversions.findOne(key).lean<IntegrationConversionDelivery>().exec();if(existing)return{delivery:existing,duplicate:true};const value=new this.conversions({...input,...key});try{await value.save();return{delivery:value.toObject(),duplicate:false}}catch(error:unknown){if(typeof error!=='object'||error===null||!('code'in error)||error.code!==11000)throw error;const raced=await this.conversions.findOne(key).lean<IntegrationConversionDelivery>().exec();if(!raced)throw error;return{delivery:raced,duplicate:true}}}
 claimConversion(workspaceId:string,id:string){return this.conversions.findOneAndUpdate({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId),status:{$in:['queued','failed']}},{$set:{status:'processing'},$inc:{attemptCount:1}},{new:true}).lean<IntegrationConversionDelivery>().exec()}
 updateConversion(workspaceId:string,id:string,update:object){return this.conversions.updateOne({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId)},update)}
 async conversion(workspaceId:string,connectionId:string,id:string){const value=await this.conversions.findOne({_id:new Types.ObjectId(id),workspaceId:new Types.ObjectId(workspaceId),connectionId:new Types.ObjectId(connectionId)}).lean<IntegrationConversionDelivery>().exec();if(!value)throw new NotFoundException('Meta conversion delivery not found');return value}
}
