import { BadRequestException, Injectable } from '@nestjs/common';
import { createHash } from 'node:crypto';
import type { ProviderConnectionContext } from '../../types/provider-adapter.js';
import { MetaApiClient } from './meta-api.client.js';
export interface MetaCustomerInformation{email?:string;phone?:string;firstName?:string;lastName?:string;city?:string;state?:string;postalCode?:string;country?:string;externalId?:string;clientIpAddress?:string;clientUserAgent?:string;fbp?:string;fbc?:string}
export interface MetaConversionInput{eventName:string;eventTime:Date;eventId:string;actionSource:'website'|'app'|'phone_call'|'chat'|'email'|'physical_store'|'system_generated'|'other';eventSourceUrl?:string;customer:MetaCustomerInformation;customData?:Record<string,unknown>;testEventCode?:string}
export interface PreparedMetaConversion{event_name:string;event_time:number;event_id:string;action_source:string;event_source_url?:string;user_data:Record<string,string|string[]>;custom_data:Record<string,unknown>}
@Injectable()
export class MetaConversionsService{
 constructor(private readonly client:MetaApiClient){}
 prepare(input:MetaConversionInput):PreparedMetaConversion{const userData:Record<string,string|string[]>={},hashed:[keyof MetaCustomerInformation,string,boolean][]=[['email','em',true],['phone','ph',false],['firstName','fn',true],['lastName','ln',true],['city','ct',true],['state','st',true],['postalCode','zp',true],['country','country',true],['externalId','external_id',true]];for(const[source,target,lowercase]of hashed){const raw=input.customer[source];if(typeof raw!=='string'||!raw.trim())continue;const normalized=source==='phone'?raw.replace(/\D/gu,''):lowercase?raw.trim().toLowerCase():raw.trim();if(normalized)userData[target]=[this.hash(normalized)];}for(const[source,target]of [['clientIpAddress','client_ip_address'],['clientUserAgent','client_user_agent'],['fbp','fbp'],['fbc','fbc']]as const){const value=input.customer[source];if(value)userData[target]=value;}if(Object.keys(userData).length===0)throw new BadRequestException('At least one customer identifier is required for Meta Conversions API');return{event_name:input.eventName,event_time:Math.floor(input.eventTime.getTime()/1000),event_id:input.eventId,action_source:input.actionSource,...(input.eventSourceUrl?{event_source_url:input.eventSourceUrl}:{}),user_data:userData,custom_data:input.customData??{}};}
 send(context:ProviderConnectionContext,pixelId:string,event:PreparedMetaConversion,testEventCode?:string){if(!context.credentials.accessToken)throw new BadRequestException('Meta access token is unavailable');if(!(context.credentials.selectedResourceIds?.pixels??[]).includes(pixelId))throw new BadRequestException('Meta Pixel is not selected for this connection');return this.client.request<{events_received?:number;messages?:string[];fbtrace_id?:string}>(`${pixelId}/events`,context.credentials.accessToken,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({data:[event],...(testEventCode?{test_event_code:testEventCode}:{})})});}
 private hash(value:string){return createHash('sha256').update(value).digest('hex');}
}
