import { BarChart3, Copy, GripVertical, ListPlus, Plus, Settings2 } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Checkbox, Input, MetricCard, Select, Switch, Table, Tabs, type TableColumn } from '@/shared/ui';

interface FormItem { id: string; name: string; status: 'published' | 'draft'; submissions: number; conversion: string }
const initialForms: FormItem[] = [{ id: 'f1', name: 'Request a demo', status: 'published', submissions: 842, conversion: '24.8%' }, { id: 'f2', name: 'Newsletter signup', status: 'published', submissions: 2341, conversion: '38.1%' }, { id: 'f3', name: 'Event registration', status: 'draft', submissions: 0, conversion: '—' }];
const fieldNames = ['First name', 'Last name', 'Work email', 'Company', 'Team size'];

export function FormsPage() {
  const [forms, setForms] = useState(initialForms); const [builder, setBuilder] = useState(false); const [fields, setFields] = useState(fieldNames);
  const columns: TableColumn<FormItem>[] = [{ key: 'name', header: 'Form', render: (row) => <strong>{row.name}</strong> }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'published' ? 'success' : 'warning'}>{row.status}</Badge> }, { key: 'submissions', header: 'Submissions', align: 'right', render: (row) => row.submissions.toLocaleString() }, { key: 'conversion', header: 'Conversion', align: 'right', render: (row) => row.conversion }, { key: 'action', header: '', render: () => <Button size="sm" variant="ghost"><Copy size={15} />Embed</Button> }];
  const formList = <div className="grid gap-4"><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Total views" value="12,840" /><MetricCard label="Submissions" value="3,183" /><MetricCard label="Conversion rate" value="31.4%" /></div><Table columns={columns} getRowKey={(row) => row.id} rows={forms} /></div>;
  const formBuilder = <div className="grid min-h-[34rem] overflow-hidden rounded-xl border border-slate-200 bg-white md:grid-cols-[14rem_1fr_16rem] dark:border-slate-700 dark:bg-slate-900"><aside className="border-r border-slate-200 p-3 dark:border-slate-700"><h3 className="text-sm font-semibold">Fields</h3>{['Text', 'Email', 'Phone', 'Select', 'Checkbox', 'Date', 'File upload'].map((field) => <Button className="mt-2 w-full justify-start" key={field} onClick={() => setFields((current) => [...current, field])} size="sm" variant="outline"><Plus size={14} />{field}</Button>)}</aside><main className="bg-slate-50 p-4 dark:bg-slate-950"><div className="mx-auto max-w-lg rounded-xl bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="text-xl font-bold">Request a demo</h2><p className="mt-1 text-sm text-slate-500">Tell us about your team and goals.</p><div className="mt-5 grid gap-3">{fields.map((field, index) => <div className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 dark:border-slate-700" key={`${field}-${index}`}><GripVertical className="text-slate-400" size={16} /><Input className="flex-1" label={field} placeholder={`Enter ${field.toLowerCase()}`} /></div>)}<Button>Submit</Button></div></div></main><aside className="border-l border-slate-200 p-4 dark:border-slate-700"><h3 className="flex items-center gap-2 font-semibold"><Settings2 size={16} />Form settings</h3><Input className="mt-4" label="Form name" defaultValue="Request a demo" /><Switch className="mt-4" checked label="Enable captcha" /><Switch className="mt-4" checked={false} label="Double opt-in" /><h4 className="mt-6 text-sm font-semibold">Conditional logic</h4><Select className="mt-2" options={[{ label: 'If team size is 50+', value: 'team' }]} /><Select className="mt-2" options={[{ label: 'Show phone field', value: 'phone' }]} /></aside></div>;
  const submissions = <Table columns={[{ key: 'contact', header: 'Contact', render: (row: { name: string; email: string; date: string }) => <div><strong>{row.name}</strong><p className="text-xs text-slate-500">{row.email}</p></div> }, { key: 'date', header: 'Submitted', render: (row) => row.date }, { key: 'qualified', header: 'Qualified', render: () => <Checkbox checked label="Qualified" readOnly /> }]} getRowKey={(row) => row.email} rows={[{ name: 'Olivia Martin', email: 'olivia@northstar.com', date: 'Jul 23, 10:14' }, { name: 'Noah Williams', email: 'noah@vertex.io', date: 'Jul 23, 09:42' }]} />;
  return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-indigo-600">Lead capture</p><h1 className="text-3xl font-bold">Forms</h1><p className="text-sm text-slate-500">Build conversion-focused forms and review submissions.</p></div><Button onClick={() => { if (!builder) setForms((current) => current); setBuilder(!builder); }}><ListPlus size={16} />{builder ? 'Back to forms' : 'Build form'}</Button></header>{builder ? formBuilder : <Tabs defaultValue="forms" items={[{ label: 'Forms', value: 'forms', content: formList }, { label: 'Submissions', value: 'submissions', content: submissions }, { label: 'Analytics', value: 'analytics', content: <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={<BarChart3 />} label="Completion rate" value="72%" /><MetricCard label="Average time" value="1m 42s" /><MetricCard label="Top source" value="Organic" /></div> }]} />}</div>;
}

export default FormsPage;
