import { Transform, Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsIn, IsInt, IsMongoId, IsNumber, IsObject, IsOptional, IsString, IsUrl, Max, MaxLength, Min } from 'class-validator';
export class MetaConnectionDto { @IsMongoId() connectionId!:string; }
export class CreateMetaCampaignDto extends MetaConnectionDto { @IsString()@MaxLength(200)name!:string;@IsString()@MaxLength(100)objective!:string;@IsOptional()@IsArray()@IsString({each:true})specialAdCategories:string[]=[];@IsOptional()@IsIn(['ACTIVE','PAUSED'])status:'ACTIVE'|'PAUSED'='PAUSED';@IsOptional()@IsString()timezone='UTC'; }
export class UpdateMetaCampaignDto extends MetaConnectionDto { @IsOptional()@IsString()@MaxLength(200)name?:string;@IsOptional()@IsString()@MaxLength(100)objective?:string; }
export class MetaStatusDto extends MetaConnectionDto { @IsIn(['ACTIVE','PAUSED','ARCHIVED'])status!:'ACTIVE'|'PAUSED'|'ARCHIVED'; }
export class CreateMetaAdSetDto extends MetaConnectionDto { @IsString()name!:string;@IsInt()@Min(1)dailyBudget!:number;@IsOptional()@IsInt()@Min(1)lifetimeBudget?:number;@IsString()optimizationGoal!:string;@IsString()billingEvent!:string;@IsObject()targeting!:Record<string,unknown>;@IsOptional()@IsString()startTime?:string;@IsOptional()@IsString()endTime?:string;@IsOptional()@IsArray()@IsString({each:true})publisherPlatforms?:string[];@IsOptional()@IsArray()@IsString({each:true})facebookPositions?:string[];@IsOptional()@IsArray()@IsString({each:true})instagramPositions?:string[];@IsOptional()@IsIn(['ACTIVE','PAUSED'])status:'ACTIVE'|'PAUSED'='PAUSED'; }
export class UpdateMetaAdSetDto extends MetaConnectionDto { @IsOptional()@IsString()name?:string;@IsOptional()@IsInt()@Min(1)dailyBudget?:number;@IsOptional()@IsInt()@Min(1)lifetimeBudget?:number;@IsOptional()@IsString()optimizationGoal?:string;@IsOptional()@IsString()billingEvent?:string;@IsOptional()@IsObject()targeting?:Record<string,unknown>;@IsOptional()@IsString()startTime?:string;@IsOptional()@IsString()endTime?:string; }
export class CreateMetaAdDto extends MetaConnectionDto { @IsString()name!:string;@IsString()adSetId!:string;@IsString()creativeId!:string;@IsOptional()@IsIn(['ACTIVE','PAUSED'])status:'ACTIVE'|'PAUSED'='PAUSED'; }
export class UpdateMetaAdDto extends MetaConnectionDto { @IsOptional()@IsString()name?:string;@IsOptional()@IsString()creativeId?:string; }
export class CreateMetaCreativeDto extends MetaConnectionDto { @IsString()name!:string;@IsString()pageId!:string;@IsOptional()@IsString()instagramActorId?:string;@IsString()primaryText!:string;@IsString()headline!:string;@IsOptional()@IsString()description?:string;@IsUrl({require_tld:false})destinationUrl!:string;@IsString()callToAction!:string;@IsMongoId()mediaFileId!:string; }
export class CreateMetaLookalikeDto extends MetaConnectionDto { @IsString()name!:string;@IsString()sourceAudienceId!:string;@IsString()country!:string;@IsNumber()@Min(0.01)ratio!:number; }
export class CreateMetaCustomAudienceDto extends MetaConnectionDto { @IsString()name!:string;@IsOptional()@IsString()description?:string;@IsOptional()@IsIn(['USER_PROVIDED_ONLY','PARTNER_PROVIDED_ONLY','BOTH_USER_AND_PARTNER_PROVIDED'])customerFileSource:'USER_PROVIDED_ONLY'|'PARTNER_PROVIDED_ONLY'|'BOTH_USER_AND_PARTNER_PROVIDED'='USER_PROVIDED_ONLY'; }
export class MetaInsightsQueryDto extends MetaConnectionDto { @IsDateString()since!:string;@IsDateString()until!:string;@IsOptional()@IsIn(['account','campaign','adset','ad'])level:'account'|'campaign'|'adset'|'ad'='campaign';@IsOptional()@Transform(({value})=>value===true||value==='true')@IsBoolean()daily=false;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)@Max(100)limit=50;@IsOptional()@IsString()cursor?:string; }
