import { Activity, Bot, Building2, CreditCard, Flag, Headphones, Search, Server, Users } from 'lucide-react';
import { useState } from 'react';
import { Badge, Button, Input, MetricCard, Select, Switch, Table, Tabs } from '@/shared/ui';

const users = [{ name: 'Alex Morgan', email: 'alex@acme.io', workspace: 'Acme Studio', status: 'Active' }, { name: 'Olivia Martin', email: 'olivia@northstar.io', workspace: 'Northstar Labs', status: 'Active' }, { name: 'Ethan Clark', email: 'ethan@lumon.co', workspace: 'Lumon Digital', status: 'Suspended' }];
const workspaces = [{ name: 'Acme Studio', plan: 'Growth', members: 11, contacts: '32.8k' }, { name: 'Northstar Labs', plan: 'Scale', members: 28, contacts: '118k' }, { name: 'Lumon Digital', plan: 'Starter', members: 3, contacts: '4.2k' }];

export function AdminPage() {
  const [search, setSearch] = useState('');
  const userTable = <Table columns={[{ key: 'user', header: 'User', render: (row: typeof users[number]) => <div><strong>{row.name}</strong><p className="text-xs text-slate-500">{row.email}</p></div> }, { key: 'workspace', header: 'Workspace', render: (row) => row.workspace }, { key: 'status', header: 'Status', render: (row) => <Badge tone={row.status === 'Active' ? 'success' : 'danger'}>{row.status}</Badge> }, { key: 'action', header: '', render: () => <Button size="sm" variant="ghost">View</Button> }]} getRowKey={(row) => row.email} rows={users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(search.toLowerCase()))} />;
  const workspaceTable = <Table columns={[{ key: 'name', header: 'Workspace', render: (row: typeof workspaces[number]) => <strong>{row.name}</strong> }, { key: 'plan', header: 'Plan', render: (row) => <Badge tone="primary">{row.plan}</Badge> }, { key: 'members', header: 'Members', render: (row) => row.members }, { key: 'contacts', header: 'Contacts', render: (row) => row.contacts }]} getRowKey={(row) => row.name} rows={workspaces} />;
  const health = <div className="grid gap-4 md:grid-cols-2">{['Web application', 'Mock API service', 'Background worker', 'Queue service', 'Email provider', 'File storage'].map((service, index) => <article className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" key={service}><span className={`size-3 rounded-full ${index === 4 ? 'bg-amber-500' : 'bg-emerald-500'}`} /><div><strong className="text-sm">{service}</strong><p className="text-xs text-slate-500">{index === 4 ? 'Degraded mock status' : 'Operational'}</p></div><span className="ml-auto text-xs text-slate-500">{index === 4 ? '320 ms' : '42 ms'}</span></article>)}</div>;
  const flags = <div className="grid gap-3">{['New analytics experience', 'AI agent marketplace', 'Advanced attribution', 'Experimental workflow nodes'].map((flag, index) => <div className="flex items-center rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" key={flag}><div><strong className="text-sm">{flag}</strong><p className="text-xs text-slate-500">Controlled frontend feature rollout.</p></div><Switch checked={index < 2} className="ml-auto" label="" /></div>)}</div>;
  return <div className="grid gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-red-600">Platform administration</p><h1 className="text-3xl font-bold">Admin</h1><p className="text-sm text-slate-500">Monitor platform accounts, usage, health, and rollout controls.</p></div><Select aria-label="Environment" options={[{ label: 'Production', value: 'prod' }, { label: 'Staging', value: 'staging' }]} /></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={<Users />} label="Total users" value="12,842" /><MetricCard icon={<Building2 />} label="Workspaces" value="2,418" /><MetricCard icon={<CreditCard />} label="Monthly revenue" value="$428k" /><MetricCard icon={<Bot />} label="AI usage" value="18.4M" /></div><Input leading={<Search size={16} />} onChange={(event) => setSearch(event.target.value)} placeholder="Search platform records…" value={search} /><Tabs defaultValue="users" items={[{ label: 'Users', value: 'users', content: userTable }, { label: 'Workspaces', value: 'workspaces', content: workspaceTable }, { label: 'Subscriptions', value: 'subscriptions', content: <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Starter" value="1,204" /><MetricCard label="Growth" value="942" /><MetricCard label="Scale" value="272" /></div> }, { label: 'AI usage', value: 'ai', content: <div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Tokens simulated" value="18.4M" /><MetricCard label="Agent sessions" value="84,220" /><MetricCard label="Avg cost/workspace" value="$12.40" /></div> }, { label: 'System health', value: 'health', content: health }, { label: 'Support', value: 'support', content: <Table columns={[{ key: 'ticket', header: 'Ticket', render: (row: { id: string; workspace: string; priority: string }) => <strong>{row.id}</strong> }, { key: 'workspace', header: 'Workspace', render: (row) => row.workspace }, { key: 'priority', header: 'Priority', render: (row) => <Badge tone={row.priority === 'High' ? 'danger' : 'warning'}>{row.priority}</Badge> }]} getRowKey={(row) => row.id} rows={[{ id: 'SUP-4821', workspace: 'Northstar Labs', priority: 'High' }, { id: 'SUP-4818', workspace: 'Acme Studio', priority: 'Normal' }]} /> }, { label: 'Feature flags', value: 'flags', content: flags }]} /><div className="sr-only"><Activity /><Flag /><Headphones /><Server /></div></div>;
}

export default AdminPage;
