import type { SearchEntity, SearchScalarType } from './search.types.js';
export interface SearchEntitySchema {
  collection: string;
  fields: Readonly<Record<string, SearchScalarType>>;
  sortable: ReadonlySet<string>;
  textFields: readonly string[];
  atlasIndex: string;
}
const common = {
  createdAt: 'date',
  updatedAt: 'date',
  createdBy: 'objectId',
  updatedBy: 'objectId',
} as const;
export const SEARCH_SCHEMAS: Readonly<Record<SearchEntity, SearchEntitySchema>> = {
  contacts: {
    collection: 'contacts',
    fields: {
      ...common,
      displayName: 'string',
      lifecycleStatus: 'string',
      source: 'string',
      ownerId: 'objectId',
      tags: 'stringArray',
      dataQualityScore: 'number',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'displayName', 'dataQualityScore']),
    textFields: [
      'displayName',
      'firstName',
      'lastName',
      'emailAddresses.value',
      'phoneNumbers.value',
    ],
    atlasIndex: 'contacts_search',
  },
  companies: {
    collection: 'companies',
    fields: {
      ...common,
      name: 'string',
      domain: 'string',
      industry: 'string',
      size: 'string',
      ownerId: 'objectId',
      tags: 'stringArray',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'name', 'domain']),
    textFields: ['name', 'domain', 'industry'],
    atlasIndex: 'companies_search',
  },
  leads: {
    collection: 'leads',
    fields: {
      ...common,
      name: 'string',
      normalizedEmail: 'string',
      normalizedPhone: 'string',
      source: 'string',
      score: 'number',
      qualification: 'string',
      status: 'string',
      ownerId: 'objectId',
      followUpAt: 'date',
      tags: 'stringArray',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'name', 'score', 'followUpAt']),
    textFields: ['name', 'email', 'phone'],
    atlasIndex: 'leads_search',
  },
  deals: {
    collection: 'deals',
    fields: {
      ...common,
      title: 'string',
      value: 'number',
      currency: 'string',
      pipelineId: 'objectId',
      stageId: 'objectId',
      probability: 'number',
      status: 'string',
      ownerId: 'objectId',
      expectedCloseDate: 'date',
      deletedAt: 'date',
    },
    sortable: new Set([
      'createdAt',
      'updatedAt',
      'title',
      'value',
      'probability',
      'expectedCloseDate',
    ]),
    textFields: ['title'],
    atlasIndex: 'deals_search',
  },
  tasks: {
    collection: 'tasks',
    fields: {
      ...common,
      title: 'string',
      status: 'string',
      priority: 'string',
      dueAt: 'date',
      ownerId: 'objectId',
      contactId: 'objectId',
      companyId: 'objectId',
      dealId: 'objectId',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'title', 'dueAt', 'priority']),
    textFields: ['title', 'description'],
    atlasIndex: 'tasks_search',
  },
  conversations: {
    collection: 'conversations',
    fields: {
      ...common,
      status: 'string',
      channel: 'string',
      unreadCount: 'number',
      lastMessageAt: 'date',
      assigneeIds: 'stringArray',
      labelIds: 'stringArray',
      snoozedUntil: 'date',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'lastMessageAt', 'unreadCount']),
    textFields: ['subject', 'searchText'],
    atlasIndex: 'conversations_search',
  },
  campaigns: {
    collection: 'campaigns',
    fields: {
      ...common,
      name: 'string',
      channel: 'string',
      status: 'string',
      approvalStatus: 'string',
      scheduledAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'name', 'scheduledAt', 'status']),
    textFields: ['name'],
    atlasIndex: 'campaigns_search',
  },
  workflows: {
    collection: 'workflow_definitions',
    fields: { ...common, name: 'string', status: 'string', latestVersion: 'number' },
    sortable: new Set(['createdAt', 'updatedAt', 'name', 'latestVersion']),
    textFields: ['name', 'description'],
    atlasIndex: 'workflows_search',
  },
  appointments: {
    collection: 'appointments',
    fields: {
      ...common,
      customerId: 'objectId',
      staffId: 'objectId',
      serviceId: 'objectId',
      startAt: 'date',
      endAt: 'date',
      status: 'string',
      timezone: 'string',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'startAt', 'endAt', 'status']),
    textFields: ['location', 'notes'],
    atlasIndex: 'appointments_search',
  },
  files: {
    collection: 'files',
    fields: {
      ...common,
      originalName: 'string',
      mimeType: 'string',
      extension: 'string',
      size: 'number',
      status: 'string',
      scanStatus: 'string',
      processingStatus: 'string',
      folder: 'string',
      tags: 'stringArray',
      deletedAt: 'date',
    },
    sortable: new Set(['createdAt', 'updatedAt', 'originalName', 'size', 'status']),
    textFields: ['originalName', 'folder', 'tags'],
    atlasIndex: 'files_search',
  },
};
